Add select widget with examples
contao/docs pull request #1038
Opened 2022-04-29 13:51 UTC by bezin

2022-04-29 13:51 UTC, bezin commented
See #743

2022-05-01 16:27 UTC, fritzmg commented on docs/dev/reference/widgets/select.md
> +    'label' => 'Visibility', 'Whether this element is visible on the page'],
```suggestion
    'label' => ['Visibility', 'Whether this element is visible on the page'],

```

2022-05-01 16:27 UTC, fritzmg commented on docs/dev/reference/widgets/select.md
> +    'options' => [ 'always', 'never', 'auto' ],
```suggestion
    'options' => ['always', 'never', 'auto'],

```

2022-05-01 16:28 UTC, fritzmg requested changes

2022-05-01 16:28 UTC, fritzmg commented on docs/dev/reference/widgets/select.md
> +        'notnull' => true,
```suggestion

```
Since this is the default I don't think we have to include it.

2022-05-01 16:28 UTC, fritzmg commented on docs/dev/reference/widgets/select.md
> +        'notnull' => true,
```suggestion

```

2022-05-01 16:28 UTC, fritzmg commented on docs/dev/reference/widgets/select.md
> +        'notnull' => true,
```suggestion

```

2022-05-04 12:59 UTC, fritzmg approved these changes

2022-05-04 12:59 UTC, merged

2022-05-04 12:59 UTC, fritzmg commented
Thank you @bezin :)