Add file tree widget documentation
contao/docs pull request #1081
Opened 2022-09-23 07:13 UTC by koertho

This PR add the documentation for the file tree widget. 

Notes:
- since I haven't tried contao 5 yet, I do not know if there are more changes to this widget
- I found a deprecation for orderField so I added a deprecation notice in style of the other notices. Since there is no tag for this, I copied the html. I think we need a deprecation tag here, so we can replace this later.
- in core-bundle tl_content multiSRC field has the multiple eval flag to true, but from my knowledge this is not necessary, isn't it?
- this time I got it compiled local and look good for me :)

P.S.: sorry @fritzmg that I took over your work :)

2022-09-23 13:38 UTC, fritzmg commented
> in core-bundle tl_content multiSRC field has the multiple eval flag set to true, but from my knowledge this is not necessary, isn't it?

Why would it not be necessary? Or do you mean that `'fieldType' => 'checkbox'` is enough and it works even without `'multiple' => true`?

2022-09-23 13:40 UTC, fritzmg requested changes
Some minor code style adjustments :)

2022-09-23 13:40 UTC, fritzmg commented on docs/dev/reference/widgets/file-tree.md
> +[
```suggestion
'singleSRC' => [

```

2022-09-23 13:40 UTC, fritzmg commented on docs/dev/reference/widgets/file-tree.md
> +'folders'         => [
```suggestion
'folders' => [

```

2022-09-26 07:33 UTC, koertho commented
> > in core-bundle tl_content multiSRC field has the multiple eval flag set to true, but from my knowledge this is not necessary, isn't it?
> 
> Why would it not be necessary? Or do you mean that `'fieldType' => 'checkbox'` is enough and it works even without `'multiple' => true`?

I tried it and it is necassary, I will add it. I though checkbox/ radio will be enough.

2022-09-26 08:24 UTC, koertho commented
I added the multiple flat, fixed code style, added eval prefix to the eval fields and sorted the keys alphabetical.

2022-09-26 08:28 UTC, fritzmg requested changes

2022-09-26 08:28 UTC, fritzmg commented on docs/dev/reference/widgets/file-tree.md
> +
```suggestion

This table only shows the options relevant to the core functionality of this widget. See the DCA reference for a [full field reference](../../dca/fields).

```

2022-09-26 08:28 UTC, fritzmg commented on docs/dev/reference/widgets/file-tree.md
> +An image gallery picker, allows picking multiple images, display them in the backend as gallery and be able to sort them.
```suggestion
An image gallery picker, allows picking multiple images, display them in the back end as gallery and be able to sort them.

```

2022-09-26 08:28 UTC, fritzmg commented on docs/dev/reference/widgets/file-tree.md
> +This widget renders a file picker allowing choosing one or more files from the file system.
```suggestion
This widget renders a file picker allowing to choose one or more files from the file system.

```

2022-09-26 08:35 UTC, fritzmg commented
Could you also provide a screenshot of the file tree widget in the gallery content element for example? So that we have an example for `isGallery => true`.

2022-09-26 09:02 UTC, fritzmg approved these changes

2022-09-26 09:02 UTC, merged

2022-09-26 09:02 UTC, fritzmg commented
Thank you very much :)