Add description for license URL
contao/docs pull request #1094
Opened 2022-11-07 17:22 UTC by ThomasJanotta

Add description for license URL

2022-11-08 09:54 UTC, fritzmg requested changes

2022-11-08 09:54 UTC, fritzmg commented on docs/manual/file-manager/meta-data.en.md
> +The license URL is displayed on the corresponding page on which the image is embedded in [JSON-LD format](https://en.wikipedia.org/wiki/JSON-LD") as [SCHEMA-ImageObject entry](https://schema.org/Imag
```suggestion
On the page on which the image is embedded the license URL is used in the [SCHEMA-ImageObject](https://schema.org/ImageObject "SCHEMA-ImageObject") of the [JSON-LD](https://en.wikipedia.org/wiki/JSON-LD") to comply with licensing notices.
```

2022-11-08 09:54 UTC, fritzmg commented on docs/manual/file-manager/meta-data.en.md
> +To specify the license URL under the image on the page, you can add the following code to the image.html5 template:
```suggestion
To display the license URL under the image on the page you can add the following code to the `image.html5` template:
```

2022-11-08 09:54 UTC, fritzmg commented on docs/manual/file-manager/meta-data.en.md
> +<?php if($this->license): ?><p class="ce_image__license" ><?= $this->license ?></p><?php endif; ?>
```suggestion
<?php if ($this->license): ?><p class="ce_image__license" ><?= $this->license ?></p><?php endif; ?>
```

2022-11-08 15:47 UTC, ThomasJanotta commented
OK

2022-11-08 17:30 UTC, fritzmg approved these changes

2022-12-01 09:54 UTC, netzarbeiter approved these changes
Thank you, Thomas

2022-12-01 09:54 UTC, merged