Add more detailed notice for environment variables
contao/docs pull request #1128
Opened 2023-01-12 19:46 UTC by JanMalte

2023-01-12 23:31 UTC, fritzmg reviewed
Not really sure this is necessary as nothing bad will happen if you use both.

2023-01-12 23:43 UTC, JanMalte commented
I just translated and added the text from the english version:
https://docs.contao.org/dev/reference/config/#environment-variables-for-the-contao-managed-edition

2023-01-26 13:41 UTC, netzarbeiter requested changes
Thank you, Jan

2023-01-26 13:41 UTC, netzarbeiter commented on docs/manual/system/settings.de.md
> +in der `config/parameters.yaml` und daher solltest du diese Parameter nicht verwendet werden, wenn du stattdessen die Umgebungsvariable
```suggestion
in der `config/parameters.yaml` und daher sollten diese Parameter nicht verwendet werden, wenn du stattdessen die Umgebungsvariable 
```

2023-02-22 16:38 UTC, netzarbeiter commented
I am closing this ticket because of the following [PR](https://github.com/contao/docs/pull/1133).

2023-02-22 16:38 UTC, closed without merging