Update pages-as-central-elements.en.md
contao/docs pull request #1145
Opened 2023-02-12 09:13 UTC by Ioan-Popa

Wording and grammar improvements.

2023-02-12 13:39 UTC, fritzmg requested changes

2023-02-12 13:39 UTC, fritzmg commented on docs/manual/layout/site-structure/pages-as-central-elements.en.md
> +| Starting point of a website | A page of this type is the starting point of a website within the page structure. A Contao instance can manage multiple websites, which can, for example. have differen
```suggestion
| Starting point of a website | A page of this type is the starting point of a website within the page structure. A Contao instance can manage multiple websites, which can, for example, have different languages or run completely independently under different domains (multi-domain operation). |
```

2023-02-12 13:39 UTC, fritzmg commented on docs/manual/layout/site-structure/pages-as-central-elements.en.md
> +| 401 Not authenticated | {{< version-tag "4.6" >}} This page appears when a visitor is not logged in and is therefore not allowed to access a protected page. You can choose to use the page as a regu
Instead of "appears" may be we should say "rendered", wdyt?

2023-02-12 13:39 UTC, fritzmg commented on docs/manual/layout/site-structure/pages-as-central-elements.en.md
> +| 403 Access denied | This page appears if a user is logged in, but does not have the necessary access rights to access a protected page. You can choose to use the page as a regular page and display
Front end users in Contao are called "members" so may be we should keep the terminology here.

2024-02-07 14:37 UTC, netzarbeiter commented
In favour of PR #1145

2024-02-07 14:37 UTC, closed without merging