Document time period widget
contao/docs pull request #1164
Opened 2023-03-23 10:38 UTC by koertho

This PR documents the time period widget.

2023-03-24 12:04 UTC, fritzmg requested changes

2023-03-24 12:04 UTC, fritzmg commented on docs/dev/reference/widgets/time-period.md
> +| options        | array                | The options for select menu, typical the time units like `['s', 'm', 'h']`  |
```suggestion
| options        | array                | The options for select menu, typically time units like `['s', 'm', 'h']`  |

```

2023-03-24 12:04 UTC, fritzmg commented on docs/dev/reference/widgets/time-period.md
> +| reference      | array                | The translation array (typical `&$GLOBALS['TL_LANG']['MSC']['timePeriod']`) |
```suggestion
| reference      | array                | The translation array (typically `&$GLOBALS['TL_LANG']['MSC']['timePeriod']`) |

```

2023-03-24 12:04 UTC, fritzmg commented on docs/dev/reference/widgets/time-period.md
> +| eval.maxlength | int                  | Maximum number of characters that is allowed in the current field.          |
```suggestion
| eval.maxlength | int                  | Maximum number of characters allowed in the current field.          |

```

2023-03-24 12:04 UTC, fritzmg commented on docs/dev/reference/widgets/time-period.md
> +Values are stored as serialized array, so using blob is prefered.
```suggestion
Values are stored as a serialized array, so using blob is preferred.

```

2023-03-27 08:55 UTC, koertho commented
Applied your suggestions :)

2023-03-27 17:03 UTC, fritzmg approved these changes

2023-03-27 17:03 UTC, merged

2023-03-27 17:03 UTC, fritzmg commented
Thank you @koertho :)