Avoid belittling words
contao/docs pull request #117
Opened 2019-10-25 15:43 UTC by Toflar

I did the same PR for the Symfony docs and I think it applies to us as well (in fact I'm convinced it applies for any documentation).

2019-10-25 16:09 UTC, fiedsch commented
I line the PR but think it might be over the top in some places by "simply" removing the belittling words. 
Example: in `docs/dev/framework/caching.md` 
    Moreover, you don't have to register to all the different callbacks such as `onsubmit_callback` or `ondelete_callback`.

You can ~~simply~~ register to the [`oninvalidate_cache_tags` callback][5] and add your own tags.	You can register to the [`oninvalidate_cache_tags` callback][5] and add your own tags.

I understand the simply like "it suffices to ..." which I would not consider belittling, but it slightly changes the sense of the sentence.

Of course just my 2ct.

2019-10-25 17:07 UTC, xchs submitted a review, later dismissed

2019-10-28 08:16 UTC, Toflar commented
> I understand the "simply" like "it suffices to ..." which I would not consider belittling, but it slightly changes the sense of the sentence.

Of course it depends on the meaning. I agree. But at the same time even when used "correctly" it mostly doesn't bring any additional information to the sentence. So by removing all of them, it's easier to track down the bad ones :)

2019-10-29 09:23 UTC, fritzmg requested changes

2019-10-29 09:23 UTC, fritzmg commented on docs/dev/framework/cron.md
> +To register your job, add another array item with the class and method
may be `your own job` here

2019-10-29 09:23 UTC, fritzmg commented on docs/dev/getting-started/extension.md
>  the extension is still pretty empty.
What about `pretty` here? :) May be use `almost` instead?

2019-10-29 09:24 UTC, fritzmg commented
👍 

I actually wanted to incorporate this right from the start but unfortunately forgot about it over time and did not include it in the `CONTRIBUTING.md`.

2019-10-29 09:44 UTC, Toflar commented on docs/dev/getting-started/extension.md
>  the extension is still pretty empty.
`pretty` sounds okay to me :)

2019-10-29 09:45 UTC, Toflar commented on docs/dev/framework/cron.md
> +To register your job, add another array item with the class and method
Added :)

2019-10-29 09:49 UTC, fritzmg approved these changes

2019-10-29 09:49 UTC, merged