Twig Templates Manual
contao/docs pull request #1176
Opened 2023-04-05 20:00 UTC by mlwebworker

only german language

2023-04-07 20:30 UTC, netzarbeiter approved these changes
Thank you, Maren

2023-05-01 14:46 UTC, fritzmg requested changes

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/_index.en.md
> +in the Twig templates.
```suggestion
in Twig templates.    
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-syntax.en.md
> +* `{{ ... }}` - [Output of variable](#output-of-variables)
```suggestion
* `{{ ... }}` - [Output of a variable](#output-of-variables)
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-syntax.en.md
> +is connected.
```suggestion
In the broadest sense, this refers to everything that is connected to controlling the output of variables.
```

2023-05-01 14:46 UTC, fritzmg commented on .idea/docs.iml
> +</module>
Do we need that in the repo?

2023-05-01 14:46 UTC, fritzmg commented on .idea/.gitignore
> +/dataSources.local.xml
What is this for?

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-manage.en.md
> +takes effect.
```suggestion
take effect.
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-manage.en.md
> +e.g. during the configuration of a content element. Contao distinguishes in the template folder between:
```suggestion
e.g. during the configuration of a content element. Within the template folder Contao distinguishes between:
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-manage.en.md
> +`content_element` is for example for content elements.
```suggestion
`content_element` is for content elements for example.
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-manage.en.md
> +selected in the back end of the corresponding element.
```suggestion
These template changes apply to all elements of the respective type. This is not always desired. If you want to
make changes only for certain elements, different variants of the template are required, which can then be
selected in the back end of the corresponding element.
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-manage.en.md
> +`text.html.twig` also your two variant templates to choose from.
```suggestion
`tip.html.twig` and `highlight.html.twig`. The back end now also offers your two variant templates for selection,
next to the core template.
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-manage.en.md
> +with a theme. This is the **theme folder**.
```suggestion
In the [Theme Manager](../../../theme-manager/manage-themes/) you can link an existing subfolder to a theme.
This is the **theme folder**.
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-manage.en.md
> +underscores.
```suggestion
For technical reasons the folder name must not contain an underscore 
(see [here](https://docs.contao.org/dev/framework/templates/architecture/#managed-namespace)).
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-manage.en.md
> +templates [template hierarchy](../reuse/#template-hierarchy).
```suggestion
You can only use theme specific templates to customize templates that are defined as global templates in the [template hierarchy](../reuse/#template-hierarchy).
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-manage.en.md
> +If there is a theme specific template`/templates/content_element/text/highlight.html.twig`, you can additionally use
```suggestion
If there is a theme specific template `/templates/content_element/text/highlight.html.twig`, you can additionally use
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-reuse.en.md
> +The parent templates (base templates) of the core, from extensions or application can be replaced by a
```suggestion
The parent templates (base templates) of the core, from extensions or the application can be replaced by a
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-reuse.en.md
> +applications or a global template from the folder `/templates`.
```suggestion
[global-template](../manage/#global-templates) within the `/templates` folder for all elements.
Global [variant templates](../manage/#global-variants-templates) can also be provided. A variant template adjusts a template from the core, an extension or the application - or another global template from the `/templates` folder.
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-reuse.en.md
> +In addition, [theme-specific templates](../manage/#theme-specific-templates) are available, but they do not
```suggestion
In addition, [theme specific templates](../manage/#theme-specific-templates) are available, but they do not
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-reuse.en.md
> +[debug:contao-twig command](https://docs.contao.org/dev/framework/templates/debugging/#debug-contao-twig-command).
```suggestion
[`debug:contao-twig` command](https://docs.contao.org/dev/framework/templates/debugging/#debug-contao-twig-command).   
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-reuse.en.md
> +Also note the [corresponding section in the manual](/en/cli) when using the command line command.
```suggestion
Also note the [corresponding section in the manual](/en/cli) when using the command.
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-reuse.en.md
> +`{% block text %}` block with an additional text.
```suggestion
We create a new template for the content element text via the back end and insert an additional text into the `{% block text %}` block with an additional text.
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-reuse.en.md
> +text for the "Notice" variant`.
```suggestion
If we now select the template `content_element/text/tip`, then the parent template is the template  
`/templates/content_element/text.html.twig`.  
At the beginning the text `Introductory text for all text elements` is output and additionally at the end the
text `Here is an additional closing text for the variant "Tip"`. Between these the text that we entered in TinyMCE is output.  
When using the template `content_element/text/notice`, the text `Here is an additional closing text for the
text for the "Notice" variant` is output at the end.
```

2023-05-01 14:46 UTC, fritzmg commented on docs/manual/layout/templates/twig/twig-template-reuse.en.md
> +as a variable in the parent template.
```suggestion
For most Contao components, you can assign an additional CSS ID or CSS class in the back end.  
These are set for the corresponding components. Sometimes this is not desired and you want to assign the class
only for a specific HTML tag.  
For this purpose Contao provides you with the `{{ attrs() }}` function. This function allows you to modify any HTML attributes that have been defined in the parent template.
```

2023-05-01 14:51 UTC, netzarbeiter commented on .idea/docs.iml
> +</module>
No

2023-05-01 14:51 UTC, netzarbeiter commented on .idea/.gitignore
> +/dataSources.local.xml
No

2023-05-01 17:22 UTC, fritzmg approved these changes

2023-05-02 07:26 UTC, merged