Add list operation example
contao/docs pull request #1183
Opened 2023-04-18 07:23 UTC by koertho

This PR adds an example for list operations to the dca docs.

2023-04-19 09:44 UTC, fritzmg requested changes
Unfortunately I don't think this is a good example. This might give the false impression that this prevents non-admins from deleting records. However it only hides the button - and does not prevent the actual action.

2023-04-21 07:33 UTC, koertho commented
Ok, I changed the example to a custom button and added additional explanation.
I also enhanced the code with Backend class instead of Controller class and the usage of sprintf.

2023-04-21 07:58 UTC, fritzmg requested changes

2023-04-21 07:58 UTC, fritzmg commented on docs/dev/reference/dca/callbacks.md
> +To disable the operation, you need to check for the permission additional before it is execution, for example in the operation backend module code.
```suggestion
Attention: this won't disable the operation itself, it only hides the button!
To disable the operation, you need to check for the permission additionally 
before its execution, for example in the operation code or a `config.onload` callback.
```

2023-04-21 09:29 UTC, fritzmg approved these changes

2023-04-21 09:29 UTC, merged

2023-04-21 09:29 UTC, fritzmg commented
Thank you @koertho :)