Customization of the Contao Demo
contao/docs pull request #1277
Opened 2023-12-17 13:35 UTC by fkaminski

A few basic details to customize the demo 
(DE only, translation after the review).

2023-12-17 14:26 UTC, fritzmg requested changes

2023-12-17 14:26 UTC, fritzmg commented on docs/manual/guides/contao-demo.de.md
> +Die obrige Umsetzung könntest du ohne weiteres auch direkt in Contao nutzen. Wie erwähnt, bietet »Dart Sass« aber eben noch zahlreiche,
```suggestion
Die obige Umsetzung könntest du ohne weiteres auch direkt in Contao nutzen. Wie erwähnt, bietet »Dart Sass« aber eben noch zahlreiche,
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +description: "Die Contao-Demo nutzen und anpassen."
```suggestion
description: "Die Contao Demo nutzen und anpassen."
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Du kannst auf [conta.org](https://contao.org/) die Demo einsehen und inkl. Backend Zugang testen oder du installierst dir die Contao Demo
```suggestion
Du kannst auf [contao.org](https://contao.org/) die Demo einsehen und inkl. Backend Zugang testen oder du installierst dir die Contao Demo 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Die [Contao Demo](https://demo.contao.org/contao) repräsentiert eine vollständige Webseite zwecks Darstellung der Contao Möglichkeiten.
```suggestion
Die [Contao Demo](https://demo.contao.org/contao) repräsentiert eine vollständige Website zwecks Darstellung der Contao Möglichkeiten. 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Webseite nachvollziehen.
```suggestion
Website nachvollziehen.
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Die Contao Demo benutzt .scss Dateien für die Gestaltung. Diese (bzw. nur die `app.scss`) werden direkt in den jeweiligen Contao
```suggestion
Die Contao Demo benutzt `.scss` Dateien für die Gestaltung. Diese (bzw. nur die `app.scss`) werden direkt in den jeweiligen Contao 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Theme Einstellungen genutzt und dann über Contao als finale .css Datei kompiliert und bereit gestellt.
```suggestion
Theme Einstellungen genutzt und dann über Contao als finale `.css` Datei kompiliert und bereit gestellt. 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +die .scss Dateien bearbeiten. Möchtest du z. B. die Farbwerte der Demo anpassen kannst du über die Contao [Dateiverwaltung](/de/dateiverwaltung/)
```suggestion
die `.scss` Dateien bearbeiten. Möchtest du z. B. die Farbwerte der Demo anpassen, kannst du über die Contao [Dateiverwaltung](/de/dateiverwaltung/)
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Anschluß die »`app.scss`« einmalig anfassen und speichern (s. a.: »[Sass/Less Integration](/de/anleitungen/sass-less-integration/)«).
```suggestion
Anschluss die »`app.scss`« einmalig anfassen und speichern (s. a.: »[Sass/Less Integration](/de/anleitungen/sass-less-integration/)«).
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Bibliothek unterstützt u. U. keine aktuellen» [Dart Sass](https://sass-lang.com/dart-sass/)« Leistungsmerkmale wie z. B.
```suggestion
Bibliothek unterstützt u. U. keine aktuellen »[Dart Sass](https://sass-lang.com/dart-sass/)« Leistungsmerkmale wie z. B.
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Die gilt u. U. auch für existierende SASS Erweiterungen z. B. für den »[Visual Studio Code](https://code.visualstudio.com/)» Editor etc..
```suggestion
Die gilt u. U. auch für existierende SASS Erweiterungen z. B. für den »[Visual Studio Code](https://code.visualstudio.com/)« Editor etc. 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Installation (s. u.), daher optimaler die .scss Dateien, den Anforderungen entsprechend, lokal zu kompilieren und dann nur die final
```suggestion
Installation (s. u.), daher optimaler, die `.scss` Dateien, den Anforderungen entsprechend, lokal zu kompilieren und dann nur die final 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +vorliegende .css Datei (demnach `app.css`) in Contao zu referenzieren.
```suggestion
vorliegende `.css` Datei (demnach `app.css`) in Contao zu referenzieren.
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +In Verbindung mit »[nodejs](https://nodejs.org/)« ist es günstig, die »package.json« außerhalb der Contao Verzeichnisse anzulegen. So
```suggestion
In Verbindung mit »[Node.js](https://nodejs.org/)« ist es günstig, die »`package.json`« außerhalb der Contao Verzeichnisse anzulegen. So 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +könntest du später auch weitere Contao Installationen bedienen und mußt dabei nur die jeweiligen Pfade der SCSS und CSS Verzeichnisse, relativ
```suggestion
könntest du später auch weitere Contao Installationen bedienen und musst dabei nur die jeweiligen Pfade der SCSS und CSS Verzeichnisse, relativ
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +zur »package.json«, anpassen. Weiterhin besteht die hilfreiche Möglichkeit, die »[SASS Anweisungen](https://sass-lang.com/documentation/cli/dart-sass/)«
```suggestion
zur »`package.json`«, anpassen. Weiterhin besteht die hilfreiche Möglichkeit, die »[SASS Anweisungen](https://sass-lang.com/documentation/cli/dart-sass/)« 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Wenn du die generierte »app.css« der Demo in den Contao Theme-Einstellungen nutzt, fehlen in den Browser Dev-Tools die Referenzen zu den
```suggestion
Wenn du die generierte »`app.css`« der Demo in den Contao Theme-Einstellungen nutzt, fehlen in den Browser Dev-Tools die Referenzen zu den 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +jeweiligen .scss Abschnitten. Daher werden hierzu »[Source Maps](https://sass-lang.com/documentation/cli/dart-sass/#source-maps)« benötigt,
```suggestion
jeweiligen `.scss` Abschnitten. Daher werden hierzu »[Source Maps](https://sass-lang.com/documentation/cli/dart-sass/#source-maps)« benötigt, 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +die du automatisch über SASS erstellen und während der lokalen Entwicklung nutzen kannst. Liegt die jeweilige »Source Map« ( .map ) neben der
```suggestion
die du automatisch über SASS erstellen und während der lokalen Entwicklung nutzen kannst. Liegt die jeweilige »Source Map« (`.map`) neben der
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +»app.css« vor, zeigen die Browser Dev-Tools dann direkt auf die passenden Einträge in den .scss Dateien.
```suggestion
»`app.css`« vor, zeigen die Browser Dev-Tools dann direkt auf die passenden Einträge in den `.scss` Dateien. 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +die Erstellung einer .css Datei automatisch angestoßen, sobald du Änderungen an den .scss Dateien ( inkl. SASS Partials ) speicherst, auch
```suggestion
die Erstellung einer `.css` Datei automatisch angestoßen, sobald du Änderungen an den `.scss` Dateien ( inkl. SASS Partials ) speicherst, auch 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +über die Browser Dev-Tools ( mit Workspace Freigaben ). Einmalig aktiviert, kannst du jetzt direkt Auswirkungen deiner .scss Anpassungen in
```suggestion
über die Browser Dev-Tools (mit Workspace Freigaben). Einmalig aktiviert, kannst du jetzt direkt Auswirkungen deiner `.scss` Anpassungen in 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +»`variables/_colors.scss`« die wir tatsächlich ändern bzw. überschreiben möchten.
```suggestion
»`variables/_colors.scss`«, die wir tatsächlich ändern bzw. überschreiben möchten.
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +nutzen. Hierüber werden die bestehenden Werte der SASS Varibalen nur dann heran gezogen, sofern nicht bereits eine Definition vorliegt. Dies ist aber
```suggestion
nutzen. Hierüber werden die bestehenden Werte der SASS Variablen nur dann herangezogen, sofern nicht bereits eine Definition vorliegt. Dies ist aber 
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Weiterhin wäre die Nutzung von »[@use](https://sass-lang.com/documentation/at-rules/use/)« und [@forward](https://sass-lang.com/documentation/at-rules/forward/)
```suggestion
Weiterhin wäre die Nutzung von »[@use](https://sass-lang.com/documentation/at-rules/use/)« und »[@forward](https://sass-lang.com/documentation/at-rules/forward/)«
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +»Namespaces« eingeführt. die eine eindeutige und sichere Referenzierung ermöglichen.
```suggestion
»Namespaces« eingeführt, die eine eindeutige und sichere Referenzierung ermöglichen.
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +Selbstverständlich bist du dabei, unabhängig von Contao Versionen, nicht restriktiert. So könntest du in deinem Workflow z. B. auch
```suggestion
Selbstverständlich bist du dabei, unabhängig von Contao Versionen, nicht eingeschränkt. So könntest du in deinem Workflow z. B. auch
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.de.md
> +{{% /notice %}}
```suggestion

{{% /notice %}}
```

2023-12-17 16:28 UTC, xchs commented on docs/manual/guides/contao-demo.en.md
> +description: "Use and customize the Contao-Demo."
```suggestion
description: "Use and customize the Contao Demo."
```

2024-02-03 09:41 UTC, fritzmg commented
This needs a review from the people who created the Contao Demo - or are working with it otherise. May be @sascha-mueller or @aschempp ?

2024-02-03 09:54 UTC, sascha-mueller commented
@fritzmg I don't think that would be necessary. But I can take a look at it if you want me to.

2024-02-03 10:02 UTC, sascha-mueller approved these changes

2024-02-03 10:03 UTC, aschempp reviewed
Ich finde gut etwas zur Demo zu schreiben. Die ganzen Sass-Ausführungen sind aber irgendwie nicht Demo-spezifisch, sondern eher generell wie man Layouts in Contao machen kann?

2024-02-03 10:03 UTC, aschempp commented on docs/manual/guides/contao-demo.de.md
> +Die Contao Demo kannst du über den Contao-Manager (ab Version 1.8), bei einer Neuinstallation, bequem installieren. Weiterhin
Ich würde die Manager-Version nicht erwähnen, weil ja alle immer die neuste haben.

2024-02-03 10:03 UTC, aschempp commented on docs/manual/guides/contao-demo.de.md
> +Die Vor- und Nachteile dieser Vorgehensweise, bzw. was du hierbei berücksichtigen solltest, wird im Beitrag
Ich würde nicht von Vor oder Nachteilen sprechen, hört sich etwas an als "hätte die Demo auch Nachteile". Aber der Hinweis auf den Handbuch-Bereich ist sicher gut.

2024-02-03 10:03 UTC, aschempp commented on docs/manual/guides/contao-demo.de.md
> +Damit die Änderungen an dieser ([SASS-Partial](https://sass-lang.com/guide/#partials)) Datei übernommen werden, musst du allerdings im
"An diesen … Dateien" oder?

2024-02-03 10:03 UTC, aschempp commented on docs/manual/guides/contao-demo.de.md
> +Wenn du dich aber darüber hinaus an der aktuellen» [Sass-Dokumentation](https://sass-lang.com/documentation/)« orientierst, kann es passieren,
Müssen wir das bei der Demo erwähnen? Steht das nicht (bzw. sollte) im Sass-Bereich des Handbuchs?

2024-02-03 10:24 UTC, fkaminski commented
> Ich finde gut etwas zur Demo zu schreiben. Die ganzen Sass-Ausführungen sind aber irgendwie nicht Demo-spezifisch, sondern eher generell wie man Layouts in Contao machen kann?

Nach Absprache mit Sascha hab ich es (im Demo Kontext) bewußt allgemein gehalten, da Sascha zudem eine eigene Tutorial-Serie dazu plant.

2024-02-03 10:44 UTC, fritzmg commented
I think in the context of the Demo it's ok to explain it's theming setup - though may be we should clarify, that this is not necessarily the best practise for _your_ website, as Contao is generally agnostic to that.

2024-02-03 11:08 UTC, fkaminski commented
> ... though may be we should clarify, that this is not necessarily the best practise for _your_ website, as Contao is generally agnostic to that.

Agree - Hab versucht dies in der Einleitung thematisch aufzunehmen:
_"Es werden hierbei lediglich einige der zahlreichen Optionen aufgeführt, die du zur weiteren Anpassung nutzen könntest."_

Oder evtl:
_"Es werden hierbei lediglich einige der Optionen aufgeführt, die du zur Anpassung nutzen könntest. Diese sollten als Anregungen dienen und sind unabhängig von den zahlreichen, weiteren Möglichkeiten in Contao."_

2024-02-03 16:03 UTC, fritzmg approved these changes

2024-02-07 15:32 UTC, netzarbeiter approved these changes
Thank you, Franko

2024-02-07 15:32 UTC, merged