Update system-requirements.de.md
contao/docs pull request #132
Opened 2019-10-30 14:02 UTC by netzarbeiter

#102

2019-10-31 08:48 UTC, aschempp commented
🤔 für Contao werden die aber nicht benötigt (https://github.com/contao/contao/blob/master/composer.json#L18-L26)

Und warum der Manager die benötigen sollte ist mir gerade auch nicht klar. Zumindest `composer why` sagt mir dass niemand `ext-curl` oder `ext-mbstring` benötigt 🤷‍♂

2019-10-31 08:55 UTC, Toflar commented
Beide sind m.M.n. nicht erforderlich. Aber beide sind 100% empfehlenswert, weil sie u.a. performanter als die Alternativen sind.

2019-10-31 08:57 UTC, fritzmg commented
@aschempp naja nicht alle Pakete listen ja verlässlich all ihre PHP Abhängigkeiten, oder?

2019-10-31 08:58 UTC, Toflar commented
Dann wäre das ein Fehler. Mir fällt keine ein, die `curl` oder `mbstring` zwingend braucht?

2019-10-31 08:59 UTC, fritzmg commented
`mbstring` hatten wir in der alten Doku als optionale Abhängigkeit für Contao 4 gelistet.

2019-10-31 09:01 UTC, Toflar commented
Ja eben. Wir haben ein `mbstring` Polyfill. D.h. alles funktioniert aber ist halt langsamer. Und `curl` ist immer sinnvoll. Besonders dann wohl aber der 4.9, aber wir hätten auch einen nativen `fopen()` Fallback. Wie gesagt, beide sind einfach deutlich stabiler und schneller, man sollte sie immer aktivieren.

2019-10-31 09:11 UTC, fritzmg commented
> Dann wäre das ein Fehler.

Contao listet auch nicht alle, hatten wir ja beim Entwicklertreffen festgestellt 😁 (aber die, die fehlen sollten eh immer da sein).

2019-10-31 10:22 UTC, BugBuster1701 commented
> erfordert 7, 8 oder 9

 ohne die Nummern ist aber nicht mehr sinvoll, oder?

2019-12-10 09:38 UTC, fritzmg commented
Eine weitere PHP Extension fehlt in der Liste:

* [`ext-fileinfo`](https://www.php.net/manual/en/book.fileinfo.php)

Erforderlich in Contao 4.4 so wie 4.8.

Übrigens unterstützt Contao 4.4 tatsächlich kein Imagick oder Gmagick? Dachte eigentlich schon.

2019-12-10 18:15 UTC, ausi commented
Imagick und Gmagick werden seit Contao 4.3 unterstützt.

2020-01-02 13:53 UTC, fritzmg commented
Ich habe die Änderung in 025227b nochmals aktualisiert. @ausi stimmt das so jetzt?

2020-01-02 18:14 UTC, xchs commented on docs/manual/installation/system-requirements.de.md
> +muss die PHP GD Biblothek allerdings trotzdem noch zusätzlich zur Verfügung stehen, in Contao **4.8** hingegen nicht mehr.
Typo:
```suggestion
muss die PHP GD Bibliothek allerdings trotzdem noch zusätzlich zur Verfügung stehen, in Contao **4.8** hingegen nicht mehr.
```

2020-01-04 15:18 UTC, ausi requested changes
Auch Contao 4.8 benötigt noch `ext-gd` siehe https://github.com/contao/core-bundle/issues/826#issuecomment-301756709

2020-01-04 15:18 UTC, ausi commented on docs/manual/installation/system-requirements.de.md
> +<sup>1</sup> Contao wählt automatisch eine Bildverarbeitungsbibliothek je nach Verfügbarkeit aus. In Contao **4.4**
```suggestion
<sup>1</sup> Contao wählt automatisch eine Bildverarbeitungsbibliothek je nach Verfügbarkeit aus.
```

2020-01-04 15:18 UTC, ausi commented on docs/manual/installation/system-requirements.de.md
> +muss die PHP GD Bibliothek allerdings trotzdem noch zusätzlich zur Verfügung stehen, in Contao **4.8** hingegen nicht mehr.
```suggestion
Die PHP GD Bibliothek muss allerdings trotzdem noch zusätzlich zur Verfügung stehen.
```

2020-01-04 15:18 UTC, ausi commented on docs/manual/installation/system-requirements.de.md
> +| [GD][ext-gd] (`ext-gd`)                   | **erforderlich**<sup>1</sup> | erfordert GD, Imagick oder Gmagick<sup>1</sup> |
```suggestion
| [GD][ext-gd] (`ext-gd`)                   | **erforderlich**<sup>1</sup> | **erforderlich**<sup>1</sup> |
```

2020-01-04 15:31 UTC, ausi approved these changes

2020-01-04 15:38 UTC, merged