Explain theme creation for the manager
contao/docs pull request #1347
Opened 2024-02-20 17:38 UTC by fkaminski

see #1344

2024-02-21 07:19 UTC, netzarbeiter requested changes
Thank you, Franko

2024-02-21 07:19 UTC, netzarbeiter commented on docs/manual/guides/manager-theme.de.md
> +Diese Daten deiner bestehenden Installation ehälst du über den »[Theme-Manager](/de/theme-manager/)« im Backend. Die exportierte
```suggestion
Diese Daten deiner bestehenden Installation erhälst du über den »[Theme-Manager](/de/theme-manager/)« im Backend. Die exportierte
```

2024-02-21 07:19 UTC, netzarbeiter commented on docs/manual/guides/manager-theme.de.md
> +Den aktuellen SQL-Dump deiner Installation kannst du über den [Backup Befehl](/de/cli/datenbank-backups/) auf der Konsole erstellen.
```suggestion
Den aktuellen SQL-Dump deiner Installation kannst du über den [Backup-Befehl](/de/cli/datenbank-backups/) auf der Konsole erstellen. 
```

2024-02-21 07:19 UTC, netzarbeiter commented on docs/manual/guides/manager-theme.de.md
> +Über die [Konfigurationsmöglichkeiten](/de/cli/datenbank-backups/#konfigurationsmoeglichkeiten) kannst du hierbei auch versch.
```suggestion
Über die [Konfigurationsmöglichkeiten](/de/cli/datenbank-backups/#konfigurationsmoeglichkeiten) kannst du hierbei auch verschiedene
```

2024-02-21 07:19 UTC, netzarbeiter commented on docs/manual/guides/manager-theme.de.md
> +Abschließend kopierst du die aktuelle »composer.json« deiner Installation ebenfalls in das entpackte Verzeichnis. Wenn du möchstest,
```suggestion
Abschließend kopierst du die aktuelle »composer.json« deiner Installation ebenfalls in das entpackte Verzeichnis. Wenn du möchtest,
```

2024-02-21 07:19 UTC, netzarbeiter commented on docs/manual/guides/manager-theme.de.md
> +Dein Theme Verzeichnis beinhaltet nun alle notwendigen Angaben. Du kannst das Verzeichnis jetzt als »`.zip`« Datei archivieren und
```suggestion
Dein Theme-Verzeichnis beinhaltet nun alle notwendigen Angaben. Du kannst das Verzeichnis jetzt als »`.zip`« Datei archivieren und 
```

2024-02-21 07:19 UTC, netzarbeiter commented on docs/manual/guides/manager-theme.en.md
> +## Theme-Manager
```suggestion
## Theme Manager
```

2024-02-21 07:19 UTC, netzarbeiter commented on docs/manual/guides/manager-theme.en.md
> +You can obtain this data from your existing installation via the "[theme manager](/en/layout/theme-manager/)" in the backend. The exported
```suggestion
You can obtain this data from your existing installation via the "[Theme Manager](/en/layout/theme-manager/)" in the back end. The exported
```

2024-02-21 07:56 UTC, netzarbeiter approved these changes

2024-02-21 07:58 UTC, netzarbeiter commented
I will merge it when @aschempp has approved the pull request.

2024-02-21 17:26 UTC, zoglo commented
@fkaminski 

Should we add the fact that every folder within the created zip archive will be imported into the root directory as well or would this be developer documentation
E.g. you can add a config/config.yml with settings such as legacy_routing: false 🤔 

Good example is the isotope demo: https://github.com/isotope/isotope-demo

Also, you can label the theme within the composer.json so it will appear within the selectable themes upon installation when synced with packagist:

See here: https://github.com/isotope/isotope-demo/blob/d046e56301d4a62c180c876c5d501da9612e49ec/composer.json#L3

2024-02-21 18:29 UTC, fkaminski commented
@zoglo Thank you. 
A try in the last commit ...

2024-02-21 22:51 UTC, aschempp commented on docs/manual/guides/manager-theme.de.md
> +Jedes Verzeichnis innerhalb des Archivs wird dabei in das Contao Stammverzeichnis importiert. Daher könntest du auch zusätzlich deine
Nicht nur jedes Verzeichnis, sondern alle Daten (ausser die theme.xml).

2024-02-21 22:51 UTC, aschempp commented on docs/manual/guides/manager-theme.de.md
> +Den aktuellen SQL-Dump deiner Theme Installation kannst du z. B. über den [Backup-Befehl](/de/cli/datenbank-backups/) auf der Konsole erstellen.
Nicht z.B., die Datei **muss** über den Befehl erstellt werden. Ein normaler PHPMyAdmin Export wurde zum Beispiel nicht gehen.

2024-02-21 22:51 UTC, aschempp commented on docs/manual/guides/manager-theme.de.md
> +Nützlich, für Theme Anbieter, ist hierbei die Kennzeichnung »`"type": "contao-theme"`«. Bei der Installation erscheint dein Theme unter
"Type": "contao-theme" ist zwingend, damit über den Contao Manager installiert werden kann. 

#Den Hinweis zu Packagist finde ich an dieser Stelle etwas kompliziert zu lesen. Vielleicht weglassen oder in einer eigenen Rubrik zum Thema Veröffentlichung schreiben?

2024-02-22 07:39 UTC, fkaminski commented
@aschempp Thank you. See last commit.

2024-02-22 07:42 UTC, netzarbeiter requested changes

2024-02-22 07:42 UTC, netzarbeiter commented on docs/manual/guides/manager-theme.de.md
> +Jede Datei und jedes Verzeichnis innerhalb des Archivs wird dabei in das Contao Stammverzeichnis importiert (außer der »theme.xml«). Daher könntest
```suggestion
Jede Datei und jedes Verzeichnis innerhalb des Archivs wird dabei in das Contao-Stammverzeichnis importiert (außer der »theme.xml«). Daher könntest 
```

2024-02-22 07:42 UTC, netzarbeiter commented on docs/manual/guides/manager-theme.de.md
> +Den aktuellen SQL-Dump deiner Theme Installation musst du über den [Backup-Befehl](/de/cli/datenbank-backups/) auf der Konsole erstellen. Ein
```suggestion
Den aktuellen SQL-Dump deiner Theme-Installation musst du über den [Backup-Befehl](/de/cli/datenbank-backups/) auf der Konsole erstellen. Ein 
```

2024-02-22 07:46 UTC, netzarbeiter approved these changes

2024-02-23 11:24 UTC, fkaminski commented
@aschempp Wegen:

> Über die Konfigurationsmöglichkeiten kannst du hierbei auch verschiedene Datenbanktabellen wie z. B. »tl_log« ausschließen.

Ist das in diesem Kontext (sql-dump) gestattet?

2024-02-25 17:52 UTC, zoglo commented
@fkaminski
> Ist das in diesem Kontext (sql-dump) gestattet?

It would completely skip these tables and create empty ones.

_See documentation on how to do this:_
https://docs.contao.org/manual/en/cli/db-backups/#configuration

_Code (4.13, also 5.3)_
https://github.com/contao/contao/blob/cf4a842d1c179f663881a6a575c15555d4e2933f/core-bundle/src/Doctrine/Backup/Config/AbstractConfig.php#L79-L101

2024-02-26 07:16 UTC, aschempp commented
> @aschempp Wegen:
> 
> > Über die Konfigurationsmöglichkeiten kannst du hierbei auch verschiedene Datenbanktabellen wie z. B. »tl_log« ausschließen.
> 
> Ist das in diesem Kontext (sql-dump) gestattet?

Ja das ist kein Problem. Die Tabellen würden danach leer angelegt, genau wie wenn du ein neues Contao installierst aber keine Datenbank importierst.

2024-02-26 19:56 UTC, zoglo commented on docs/manual/guides/manager-theme.de.md
> +Die Kennzeichnung `"type": "contao-theme"` ist dabei zwingend und für den Contao Manager notwendig.
Die Kennzeichnung ist für das Contao-Manager-Artefakt (Also die zip-Datei) nicht zwingend notwendig.
Sie dient als Flag, damit das "releaste" Theme, welches in Packagist registriert ist auch in der Theme-Suche im Contao-Manager erscheint.

Also
```md
Mit der Kennzeichnung `"type": "contao-theme"` kann das Theme in der Theme-Suche des Contao-Managers gefunden werden.
```

2024-02-27 08:02 UTC, fkaminski commented on docs/manual/guides/manager-theme.de.md
> +Die Kennzeichnung `"type": "contao-theme"` ist dabei zwingend und für den Contao Manager notwendig.
Laut @aschempp: 

> "Type": "contao-theme" ist zwingend, damit über den Contao Manager installiert werden kann.
https://github.com/contao/docs/pull/1347#discussion_r1498406916

2024-02-27 08:23 UTC, zoglo commented on docs/manual/guides/manager-theme.de.md
> +Die Kennzeichnung `"type": "contao-theme"` ist dabei zwingend und für den Contao Manager notwendig.
@fkaminski 👍

2024-02-27 08:46 UTC, fkaminski commented
@aschempp If it would be okay for you ...

> I will merge it when @aschempp has approved the pull request.

2024-02-27 10:49 UTC, aschempp commented on docs/manual/guides/manager-theme.de.md
> +anschließend in das obige, entpackte Verzeichnis.
Hier vielleicht noch ergänzen, dass die ZIP-Datei nur ein Backup enthalten darf, damit der Manager weiss was installiert werden soll. Wenn mehrere Dateien vorhanden sind, dann wird kein Restore über den Manager angeboten. Übrigens ist die Datei auch optional, ohne werden halt nur Dateien installiert aber keine Datenbank.

2024-02-27 10:50 UTC, aschempp commented on docs/manual/guides/manager-theme.de.md
> +Dein Theme-Verzeichnis beinhaltet nun alle notwendigen Angaben. Du kannst das Verzeichnis jetzt als »`.zip`« Datei archivieren und
Hier ist darauf zu achten, dass nicht der Theme-Ordner komprimiert wird, sondern nur die Dateien. Also nicht den Ordner komprimieren, sondern alle Dateien auswählen und diese als ZIP komprimieren.

2024-02-27 17:44 UTC, fkaminski commented
Thank you @aschempp  - See last commits

2024-02-28 07:48 UTC, aschempp approved these changes

2024-02-29 07:28 UTC, merged