Added initial version of our BC promise
contao/docs pull request #138
Opened 2019-10-31 15:16 UTC by Toflar

This is quite an important one so I've requested a few people for review.
Please feel free to notify other Contao devs if you think they would like to extend/modify this document.

2019-10-31 15:21 UTC, bytehead commented on docs/dev/internals/bc-promise.md
> +Composition over Inheritance][Composition_over_Inheritance].
Missing `[`

2019-10-31 15:23 UTC, Toflar commented on docs/dev/internals/bc-promise.md
> +Composition over Inheritance][Composition_over_Inheritance].
Fixed

2019-10-31 15:58 UTC, m-vo commented
Let's talk constructor parameters again.

Personally I think the exact dependencies I'm injecting into a class (that do not leak out via class methods) should be considered implementation detail: If I want to change an algorithm for instance, I'd like to be able to exchange `LibraryAGenerator` with `LibraryBProvider`, if I want to improve 'testability', I'd like to insert new dependencies - e.g. a `FilesystemAbstraction`.

So, when does this hurt anyone? Basically whenever there are calls to my class's constructor with a now changed (and incompatible = no respective optional parameters) signature due to...
1) ... someone creating an instance of my class.
2) ... someone calling `parent::__construct()`.

In a DI architecture where classes (services) are instantiated by the container 1) can be neglected. 2) is only the case when inheriting and there are only a few reasons someone should ever do this:

1. extending an abstract base class (`Contao\CoreBundle\Controller\ContentElement\AbstractContentElementController`)
2. extending a non-abstract class that is meant to be a building block (`Symfony\Component\Console\Command\Command`)
3. creating a fixture for testing (`Contao\CoreBundle\Fixtures\Exception\DerivedPageNotFoundException`)
4. overwriting features of a class (e.g. decorating a service & modifying bits)

Points 1) - 3) are legitimate use cases. 4), however, clearly is a misuse to me (the class is maybe simply not `final` due to point 4).

So how to work around this? Let's make an example: If I want decorate Doctrine's default `AnnotationReader` instead of  extending and overwriting it I could also implement the `Reader` interface myself. And If I need to reuse code can inject the existing `AnnotationReader` and simply delegate calls. This composition pattern works whenever there are appropriate interfaces around.

Long story short, because all of you know where this is going anyway: :smile:  I would vote for **excluding constructors from BC promise** and make **some well-thought exceptions** to this rule, namely to cover the above building blocks. Note that this is only true for the 'new' code, not the legacy classes inside `Resources/contao`.

(And imho those exceptions should be visible in code - e.g. with appropriate annotations. )

2019-10-31 16:24 UTC, qzminski submitted a review, later dismissed

2019-10-31 16:25 UTC, xchs submitted a review, later dismissed
👍

2019-10-31 16:25 UTC, xchs commented on docs/dev/internals/bc-promise.md
> +Being a project that sits on top of the Symfony full-stack framework we generally [follow the same rules as
```suggestion
Being a project that sits on top of the Symfony full-stack framework, we generally [follow the same rules as
```

2019-10-31 16:25 UTC, xchs commented on docs/dev/internals/bc-promise.md
> +We also follow the principles of [Semantic Versioning][Semver] which means that breaking changes must only be expected
```suggestion
We also follow the principles of [Semantic Versioning][Semver], which means that breaking changes must only be expected
```

2019-10-31 16:25 UTC, xchs commented on docs/dev/internals/bc-promise.md
> +developers but we also build tools ourselves which are then shipped with the core distribution of Contao.
```suggestion
developers but we also build tools ourselves, which are then shipped with the core distribution of Contao.
```

2019-10-31 17:25 UTC, leofeyer commented
I like the initial version and especially the following sentence:

> everything that is about integrating Contao into a Symfony application might be subject to change

What we could discuss:

1. Constructor arguments (see @m-vo's arguments above)
2. Composer/ScriptHandler (integrating Contao into a Symfony application)
3. ContaoManager/Plugin (integrating Contao into the Managed Edition)

2019-11-01 08:41 UTC, Toflar commented
> Constructor arguments (see @m-vo's arguments above)

I don't think I will ever agree here.



> Composer/ScriptHandler (integrating Contao into a Symfony application)

I don't think we need to mention this here. We won't be able to change that in any minor version so that must be covered by BC.



> ContaoManager/Plugin (integrating Contao into the Managed Edition)

Added.

2019-11-01 10:06 UTC, m-vo commented
> don't think I will ever agree here.

Do you mind sharing why?

2019-11-01 10:54 UTC, Toflar commented
Symfony protects all public methods that obviously includes constructors. Which makes sense because anybody can register their own services and use the classes the way they want.
And that's also the way it should be.
We cannot just adjust the constructor of e.g. a `PictureGenerator`. I might use my own instance of it with a different instance of `ResizerInterface`.

2019-11-01 14:17 UTC, richardhj submitted a review, later dismissed

2019-11-01 14:36 UTC, fritzmg submitted a review, later dismissed

2019-11-02 18:12 UTC, ausi commented
I’m not sure about the constructor arguments. For services it might make sense to exclude them from the BC promise. Should we set this to “up for discussion”?

2019-11-04 07:05 UTC, leofeyer commented
There is no "up for discussion" label in this repo, but we should definitely discuss this. I have set up a reminder for the next call.

2019-11-04 14:45 UTC, aschempp commented
I generally like the statement(s). Some thoughts:
 - we might mentions that the template _markup_ can change, but the template variables should not (the should only be extended).
 - There is at least one compiler pass that is explicitly designed to be re-used by extension developers: https://github.com/contao/contao/blob/master/core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php#L29

2019-11-21 14:38 UTC, leofeyer approved these changes

2019-11-28 15:26 UTC, leofeyer requested changes
As discussed in Mumble on November 28th, we want to add a paragraph about constructors marked as `@internal` before we merge.

2019-11-28 21:01 UTC, leofeyer submitted a review, later dismissed

2019-11-29 04:18 UTC, richardhj submitted a review, later dismissed

2019-11-29 07:07 UTC, ausi submitted a review, later dismissed

2019-11-29 07:30 UTC, aschempp commented on docs/dev/internals/bc-promise.md
> +  instance of the class but instead decorate the original service (see the tip about "Composition over Inheritance").
Can we somehow link to https://symfony.com/doc/current/service_container/service_decoration.html here?

2019-11-29 07:30 UTC, aschempp commented on docs/dev/internals/bc-promise.md
> +  the [Contao Managed Edition][Contao_ME].
I'm not sure this whole chapter is necessary if we simply mark them as `@internal`? All of the mentioned class types (except the Plugin) are also services, so they are already covered by _you should decorate a service_?

2019-11-29 07:58 UTC, leofeyer approved these changes

2019-11-29 07:59 UTC, merged