Add zwsp
contao/docs pull request #1445
Opened 2024-10-16 18:56 UTC by zonky2

2024-10-17 06:59 UTC, fritzmg requested changes

2024-10-17 06:59 UTC, fritzmg commented on docs/manual/article-management/insert-tags.de.md
> +| `[zwsp]`       | `&ZeroWidthSpace;` = zero-width space<br>breitenlose Leerzeichen - auch nullbreites Leerzeichen; siehe [Wikipedia](https://de.wikipedia.org/wiki/Breitenloses_Leerzeichen) |
```suggestion
| `[zwsp]`       | {{< version-tag "5.3" >}} `&ZeroWidthSpace;` = zero-width space<br>breitenlose Leerzeichen - auch nullbreites Leerzeichen; siehe [Wikipedia](https://de.wikipedia.org/wiki/Breitenloses_Leerzeichen) |
```

2024-10-17 08:19 UTC, fritzmg approved these changes

2024-10-24 08:50 UTC, netzarbeiter approved these changes
Thank you, Ingolf

2024-10-24 08:50 UTC, merged