Update namespaces.md
contao/docs pull request #1479
Opened 2024-11-28 15:59 UTC by Tastaturberuf

Make clear that are files not directories

2024-11-28 16:31 UTC, fritzmg requested changes
These aren't filenames - these are FQCNs.

2024-11-28 19:51 UTC, Tastaturberuf commented
Then lets change the header `example` with `FQCN`? I was not sure what that exactly means.

2024-11-29 08:23 UTC, fritzmg commented
You mean from "Example" to "Example Class Name" or "Example FQCN"?

2025-01-12 17:35 UTC, fritzmg commented
/reminder @Tastaturberuf

2025-01-27 11:45 UTC, Tastaturberuf commented
Sorry seems i'm muted this issue accidentally a while ago. I think `Example FQCN` is a good micro optimization. When i first discover the page, i don't understand it fully.

2025-06-07 16:00 UTC, closed without merging