Update Maklermodul
contao/docs pull request #157
Opened 2019-11-07 10:58 UTC by seibtph

2019-11-07 11:04 UTC, fritzmg requested changes
I haven't looked at the images yet, but may be you can provide English versions too?

2019-11-07 11:04 UTC, fritzmg commented on docs/manual/extensions/maklermodul.en.md
> +This contao themes includes layout templates for the Maklermodul.
```suggestion
These contao themes include layout templates for the Maklermodul.
```

2019-11-07 11:04 UTC, fritzmg commented on docs/manual/extensions/maklermodul.en.md
> +![Immobilienliste mit Auswahllisten im MATE Theme](/de/extensions/images/de/maklermodul_mate_liste_selects.png ':size=150') ![Immobilienliste mit Buttons im MATE Theme](/de/extensions/images/de/makle
```suggestion
![property list with mit select lists within the MATE theme](/de/extensions/images/de/maklermodul_mate_liste_selects.png ':size=150') ![property list with buttons within the MATE theme](/de/extensions/images/de/maklermodul_mate_liste_buttons.png ':size=150') ![property description within the MATE theme](/de/extensions/images/de/maklermodul_mate_details.png ':size=150')
```

2019-11-07 11:04 UTC, fritzmg commented on docs/manual/extensions/maklermodul.en.md
> +![Immobilienliste mit Auswahllisten im MATE Theme](/de/extensions/images/de/maklermodul_odd_liste_selects.png ':size=150') ![Immobilienliste mit Buttons im MATE Theme](/de/extensions/images/de/makler
```suggestion
![property list with select lists within the ODD theme](/de/extensions/images/de/maklermodul_odd_liste_selects.png ':size=150') ![property list with buttons within the ODD theme](/de/extensions/images/de/maklermodul_odd_liste_buttons.png ':size=150') ![property description within the ODD theme](/de/extensions/images/de/maklermodul_odd_details.png ':size=150')
```

2019-11-07 13:31 UTC, fritzmg submitted a review, later dismissed

2019-11-07 13:31 UTC, fiedsch commented on docs/manual/extensions/maklermodul.en.md
> +![property list with mit select lists within the MATE theme](/de/extensions/images/de/maklermodul_mate_liste_selects.png ':size=150') ![property list with buttons within the MATE theme](/de/extension
remove "mit"

2019-11-15 09:24 UTC, fritzmg requested changes
Btw. please use line breaks after 80 characters, or 120 characters at the most.

2019-11-26 10:10 UTC, seibtph commented
> Btw. please use line breaks after 80 characters, or 120 characters at the most.

Thanks, I have changed this.

2019-11-26 10:33 UTC, netzarbeiter requested changes
Thank you @seibtph, can you please make the changes.

2019-11-26 10:33 UTC, netzarbeiter commented on docs/manual/extensions/animated-timeline.de.md
> +Das Animated Timeline Bundle ist eine jQuery-Erweiterung für Contao 4 auf Basis von jQuery Roadmap, mit der man Inhalte
Can you please replace «jQuery Roadmap» with «jQuery-Roadmap».

2019-11-26 10:33 UTC, netzarbeiter commented on docs/manual/extensions/maklermodul.de.md
> +![Immobilienliste mit Auswahllisten im MATE Theme](/de/extensions/images/de/maklermodul_mate_liste_selects.png ':size=150')
Can you please remove « ':size=150'» in every image tag. If it is really necessary to resize the image, you will find the correct syntax in the [documentation](https://themes.gohugo.io//theme/hugo-theme-learn/en/cont/markdown/#resizing-image).

2019-11-26 11:04 UTC, netzarbeiter approved these changes

2019-11-27 15:25 UTC, fritzmg approved these changes

2019-11-27 15:27 UTC, merged