Explain 2FA for back end users
contao/docs pull request #165
Opened 2019-11-13 05:25 UTC by richardhj

The config to enforce 2FA changed since it was explained here: https://github.com/contao/core-bundle/pull/1545#issue-193781960

2019-11-13 06:33 UTC, fritzmg requested changes
Can you also provide the English translation? If not, I'll add it.

2019-11-13 06:33 UTC, fritzmg commented on docs/manual/user-management/users.de.md
> +einer Zwei-Faktor-App wie z.B. 1Password, Authy, Google Authenticator, Microsoft Authenticator, LastPass Authenticator oder
```suggestion
einer Zwei-Faktor-App wie z. B. 1Password, Authy, Google Authenticator, Microsoft Authenticator, LastPass Authenticator oder 
```

2019-11-13 07:01 UTC, richardhj commented
> Can you also provide the English translation? If not, I'll add it.

Will do

2019-11-13 07:03 UTC, richardhj commented
Where is the English document?

2019-11-13 07:04 UTC, fritzmg commented
> Where is the English document?

Ah sorry, actually you don't have to, because the whole English translation for this page does not exist yet ;)

2019-11-13 07:04 UTC, fritzmg submitted a review, later dismissed

2019-11-14 00:15 UTC, xchs requested changes

2019-11-14 00:15 UTC, xchs commented on docs/manual/user-management/users.de.md
> +und Passwort muss ein Verifizierungscode ("Time-based One-time Password") eingegeben werden. Dieses Einmalpasswort muss
```suggestion
und Passwort muss ein Verifizierungscode (»Time-based One-time Password«) eingegeben werden. Dieses Einmalpasswort muss 
```

2019-11-15 13:44 UTC, netzarbeiter approved these changes
Thank you @richardhj

2019-11-15 13:45 UTC, merged