Add translations article
contao/docs pull request #185
Opened 2019-11-21 23:00 UTC by fritzmg

2019-11-23 11:03 UTC, Toflar commented
Great work! What I'm missing is a note about the general way of using translations in Symfony. You can use the regular Symfony translator but for legacy reasons there's also the translation handling of Contao. Something like that, do you know what I mean? Some more general info to answer the question of "why the heck do I even have to use the Contao translation stuff?".

2019-11-24 10:37 UTC, fritzmg commented
Something like this: 242da8f74b8a9669430cb8b225e2c3cfcacfc3e6 ?

2019-11-24 13:35 UTC, xchs requested changes
LGTM! 👍

2019-11-24 13:35 UTC, xchs commented on docs/dev/framework/translations.md
> +| `FMD`      | `moduels`   | Front end module labels and descriptions.  |
```suggestion
| `FMD`      | `modules`   | Front end module labels and descriptions.  |
```

2019-11-24 13:35 UTC, xchs commented on docs/dev/framework/translations.md
> +Categories and keys for for new translations can be chosen at your own discretion.
```suggestion
Categories and keys for new translations can be chosen at your own discretion. 
```

2019-11-24 13:43 UTC, xchs approved these changes

2019-11-24 14:04 UTC, Toflar approved these changes
Great work!

2019-11-24 14:39 UTC, merged