add markAsCopy and dynamicPTable to config.md
contao/docs pull request #233
Opened 2020-01-23 17:27 UTC by Tastaturberuf

2020-01-23 17:29 UTC, Tastaturberuf commented
i have the table rearanged. thats why the whitespace changes in more then two lines

2020-01-23 17:45 UTC, fritzmg commented
`markAsCopy` is a new feature and not present in Contao 4.4. Can you check in which Contao version this was added and add a note somewhere?

2020-01-23 17:46 UTC, fritzmg requested changes
`markAsCopy` is a new feature and not present in Contao 4.4. Can you check in which Contao version this was added and add a note somewhere?

2020-01-23 17:49 UTC, Tastaturberuf commented
oh crap, yes this is 4.8. i'll fix thats

2020-01-23 18:09 UTC, Tastaturberuf commented
Source: https://github.com/contao/core-bundle/commit/e45c20cc5c5b642ae0b17bc413275efc9836062e

2020-01-24 09:43 UTC, fritzmg requested changes

2020-01-24 09:43 UTC, fritzmg commented on docs/dev/reference/dca/config.md
> +| markAsCopy         | Field name (`string`)             | Mark the new record with "copy of" in this field name. Since Contao 4.6
```suggestion
| markAsCopy         | Field name (`string`)             | Appends "(copy)" to this field when copying a record (Contao __4.6__ and up).                                                                         |
```

2020-01-28 17:45 UTC, fritzmg requested changes

2020-01-28 17:45 UTC, fritzmg commented on docs/dev/reference/dca/config.md
> +| markAsCopy         | Field name (`string`)             | Mark the new record with "copy of" in this field name. Since Contao 4.6
Ich kann leider nicht direkt in deinen branch comitten, müsstest du selbst comitten ;)

2020-01-29 09:22 UTC, fritzmg approved these changes

2020-01-29 09:22 UTC, merged

2020-01-29 09:22 UTC, fritzmg commented
Thank you @Tastaturberuf :)