#30 docs for PaletteManipulator
contao/docs pull request #32
Opened 2019-05-29 20:12 UTC by simonreitinger

Hallo miteinander 😄 

Danke für die Einladung! 
Ich hab mich mal an den PaletteManipulator gemacht.

Noch ein paar allgemeine Fragen:
- Workflow: Pull Requests oder direkt auf den Master pushen?
- einfach Issues nehmen und die Doku dazu schreiben oder auf Zuweisung etc warten?

2019-05-30 08:28 UTC, fritzmg requested changes

2019-06-03 07:13 UTC, Toflar reviewed
Nice! Hab bisschen kommentiert und evtl. müsste noch die Frage von @fritzmg bezüglich der Instantiierung und mehrfachen `applyTo*()` Calls dokumentiert werden, aber ansonsten: tolle Arbeit 👏

2019-06-11 07:28 UTC, Toflar requested changes
So, ein letzter Review. Dann lasst uns das erst mal mergen so :)

2019-06-14 16:15 UTC, fritzmg approved these changes

2019-07-04 08:35 UTC, merged