Change security question to spam protection
contao/docs pull request #364
Opened 2020-05-16 13:35 UTC by fritzmg

Fixes #359

2020-05-18 12:57 UTC, Toflar approved these changes

2020-05-22 08:21 UTC, netzarbeiter requested changes
Vielen Dank, Fritz.

2020-05-22 08:21 UTC, netzarbeiter commented on docs/manual/article-management/content-elements.de.md
> +**Spam-Schutz deaktivieren:** Hier kannst du die Spam-Schutz deaktivieren (nicht empfohlen). Seit Contao 4.4
Hier kannst du den Spam-Schutz deaktivieren (nicht empfohlen).

2020-05-22 08:21 UTC, netzarbeiter commented on docs/manual/core-extensions/newsletter/frontend-modules.de.md
> +**Spam-Schutz deaktivieren:** Hier kannst du die Spam-Schutz deaktivieren (nicht empfohlen).
Hier kannst du den Spam-Schutz deaktivieren (nicht empfohlen).

2020-05-22 08:21 UTC, netzarbeiter commented on docs/manual/core-extensions/newsletter/frontend-modules.de.md
> +**Spam-Schutz deaktivieren:** Hier kannst du die Spam-Schutz deaktivieren (nicht empfohlen).
Hier kannst du den Spam-Schutz deaktivieren (nicht empfohlen).

2020-05-22 08:21 UTC, netzarbeiter commented on docs/manual/module-management/user-modules.de.md
> +**Spam-Schutz deaktivieren:** Hier kannst du die Spam-Schutz deaktivieren (nicht empfohlen). Seit Contao 4.4
Hier kannst du den Spam-Schutz deaktivieren (nicht empfohlen).

2020-05-22 08:26 UTC, fritzmg commented on docs/manual/article-management/content-elements.de.md
> +**Spam-Schutz deaktivieren:** Hier kannst du die Spam-Schutz deaktivieren (nicht empfohlen). Seit Contao 4.4
Hoppla, search & replace error ;)

2020-05-22 08:30 UTC, netzarbeiter reviewed
Perfekt

2020-05-22 08:30 UTC, merged