Fixed description for colorizeLogEntries hook
contao/docs pull request #370
Opened 2020-05-24 14:33 UTC by Tastaturberuf

Kann nicht gut in Englisch formulieren.

2020-05-24 15:30 UTC, fritzmg requested changes

2020-05-24 15:30 UTC, fritzmg commented on docs/dev/reference/hooks/colorizeLogEntries.md
> +The `colorizeLogEntries` hook is triggered when a log entry is saved. It passes
```suggestion
The `colorizeLogEntries` hook is triggered when a log entry is displayed. It passes 
```

2020-05-24 15:30 UTC, fritzmg commented on docs/dev/reference/hooks/colorizeLogEntries.md
> +a string for the label as return.
```suggestion
a string for the label as return value.
```

2020-05-25 11:36 UTC, fritzmg approved these changes

2020-05-25 11:36 UTC, merged

2020-05-25 11:36 UTC, Tastaturberuf commented
sorry has mistaken the changes und resolved without apply the commit

2020-05-25 11:40 UTC, fritzmg commented
Hm? What do you mean? Everything looks fine.

2020-05-25 11:44 UTC, Tastaturberuf commented
yep now. but yesterday i have solve (it close and ignore) your changes.