Add Notice for Google Fonts API Version
contao/docs pull request #414
Opened 2020-06-04 16:46 UTC by fkaminski

2020-06-04 16:51 UTC, fritzmg approved these changes

2020-06-05 05:16 UTC, netzarbeiter requested changes
Thank you, Franko

2020-06-05 05:16 UTC, netzarbeiter commented on docs/manual/layout/theme-manager/manage-page-layouts.de.md
> +du einen Webfont ausgewählt hast, kannst du diesen, z. B. über die Angabe der Parameter `Roboto:400,700`, hier einfügen.
```suggestion
du einen Webfont ausgewählt hast, kannst du diesen, über die Angabe der Parameter `Roboto:400,700`, hier einfügen.
```

2020-06-05 05:16 UTC, netzarbeiter commented on docs/manual/layout/theme-manager/manage-page-layouts.de.md
> +Hier kannst du eine oder mehrere [Google-Webfonts](https://fonts.google.com/) zu deiner Webseite hinzufügen. Sobald
```suggestion
Hier kannst du eine oder mehrere [Google Fonts](https://fonts.google.com/) zu deiner Webseite hinzufügen. Sobald 
```

2020-06-05 05:16 UTC, netzarbeiter commented on docs/manual/layout/theme-manager/manage-page-layouts.de.md
> +Die »Google-Font API Version 2« wird zur Zeit nicht unterstützt.
```suggestion
Die »Google Fonts API Version 2« wird zur Zeit nicht unterstützt.
```

2020-06-05 06:55 UTC, netzarbeiter commented on docs/manual/layout/theme-manager/manage-page-layouts.de.md
> +Hier kannst du eine oder mehrere [Google-Webfonts](https://fonts.google.com/) zu deiner Webseite hinzufügen. Sobald
Die offizielle Schreibweise ist [Google Fonts](https://de.wikipedia.org/wiki/Google_Fonts).

2020-06-05 06:58 UTC, merged