Add a chapter FAQ
contao/docs pull request #417
Opened 2020-06-06 15:44 UTC by fkaminski

The FAQ's for starters are unsorted within one index page (for now). 
Please review the content carefully. Some of them are i.a. just copied form community entries ...

2020-06-06 18:23 UTC, xchs commented on docs/manual/faq/_index.de.md
> +Entferne hierzu in der Tabelle »tl_user« deiner Datenbank in der Spalte »admin« den Wert »1«. Anschließend kannst
BTW: Falls es in der Tabelle »tl_user« mehrere Datensätze gibt, bei denen das Admin-Flag gesetzt ist, müsste man den Wert zunächst bei allen zurücksetzen, um anschließend im Contao Installtool einen neuen Administrator anlegen zu können.

2020-06-09 15:28 UTC, netzarbeiter requested changes

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +{{% expand "Was ist der Composer Resolver Cloud?" %}}
```suggestion
{{% expand "Was ist die Composer Resolver Cloud?" %}}
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +Der [Composer Resolver Cloud](https://composer-resolver.cloud/) erlaubt die Installation von Composer-Abhängigkeiten
```suggestion
Die [Composer Resolver Cloud](https://composer-resolver.cloud/) erlaubt die Installation von Composer-Abhängigkeiten 
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +Alle Informationen findest du unter [Über den Contao Manager](/de/installation/contao-manager/).
```suggestion
Du benötigst den Contao Manager um Contao und Erweiterung zu installieren/aktualisieren/deinstallieren. Weiterführende Informationen findest du unter [Über den Contao Manager](/de/installation/contao-manager/).
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +{{% expand "Änderungen an meinen SCSS-Dateien werden nicht übernommen." %}}
```suggestion
{{% expand "Warum werden Änderungen an meinen SCSS-Dateien nicht übernommen?" %}}
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +Hier findest du eine Sammlung der häufigsten Fragen mit entsprechenden Lösungen.
```suggestion
Hier findest du eine Sammlung der häufigsten Fragen mit den passenden Antworten. 
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +{{% expand "Ich habe mein Administrator-Passwort vergessen." %}}
```suggestion
{{% expand "Ich habe mein Administrator-Passwort vergessen, wie kann ich es zurücksetzen?" %}}
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +Falls es in der Tabelle »tl_user« mehrere Datensätze gibt, bei denen das Admin-Flag gesetzt ist, kannst du den Wert
```suggestion
Falls es in der Datenbank-Tabelle »tl_user« mehrere Datensätze gibt, bei denen das Admin-Flag gesetzt ist, kannst du den Wert 
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +{{% expand "Ich habe das Install-Tool Passwort vergessen." %}}
```suggestion
{{% expand "Ich habe das Install-Tool Passwort vergessen, wie kann ich es zurücksetzen?" %}}
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +{{% expand "Es wird keine E-Mail über mein Formular versendet." %}}
```suggestion
{{% expand "Es wird keine E-Mail über mein Formular versendet, was muss ich machen?" %}}
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +{{% expand "Wie kann ich Sprachenkürzel der URL hinzufügen" %}}
```suggestion
{{% expand "Wie kann ich das Sprachenkürzel der URL hinzufügen?" %}}
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +{{% expand "Meine Bilder werden im Frontend nicht angezeigt." %}}
```suggestion
{{% expand "Meine Bilder werden im Frontend nicht angezeigt, was kann ich machen?" %}}
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +Hier findest du alle Informationen zum Contao [Debug-Modus](/de/system/debug-modus/).
```suggestion
Du kannst den [Contao Debug-Modus](/de/system/debug-modus/) über das Backend aktivieren.
```

2020-06-09 15:28 UTC, netzarbeiter commented on docs/manual/faq/_index.de.md
> +Hier erhälst du eine Übersicht zu weiteren [Contao-Ressourcen](https://contao.org/de/netzwerk.html).
```suggestion
Weiter Contao-Ressourcen findest du auf der [Projektwebseite](https://contao.org/de/netzwerk.html).
```

2020-06-09 16:01 UTC, fkaminski commented
@netzarbeiter  
Maybe we should better structure the faq with h3-Titles - for now.
However, there are many labeling options left

2020-06-09 16:08 UTC, netzarbeiter commented
Three request are still open. If we go with the headline-tag, it should be h2 (There is only the maintitle with h1).

2020-06-15 13:06 UTC, fkaminski commented
If merged - maybe we could then leave a hint/link in:
https://contao.org/de/faq.html

2020-08-03 07:50 UTC, merged

2020-08-03 07:51 UTC, netzarbeiter commented
Thank you, @fkaminski