Start of a documentation
contao/docs pull request #449
Opened 2020-06-19 22:52 UTC by Ernestopheles

2020-06-22 13:27 UTC, netzarbeiter requested changes
Thank you Ernst

2020-06-22 13:27 UTC, netzarbeiter commented on docs/manual/extensions/notification-center.de.md
> +-von [terminal42](https://terminal42.ch)_
```suggestion
_von [terminal42](https://terminal42.ch)_
```

2020-06-22 13:27 UTC, netzarbeiter commented on docs/manual/extensions/notification-center.de.md
> +Um diese Erweiterung im Rahmen der Newsletter Verwaltung zu verwenden, müssen die Module `Newsletter abonnieren` und `Newsletter kündigen` durch die korresponierenden Module `Newsletter abonnieren (N
```suggestion
Um diese Erweiterung im Rahmen der Newsletter-Verwaltung zu verwenden, müssen die Module `Newsletter abonnieren` und `Newsletter kündigen` durch die korrespondierenden Module `Newsletter abonnieren (Notification Center)` und `Newsletter kündigen (Notification Center)` ausgetauscht werden.
```

2020-06-22 13:27 UTC, netzarbeiter commented on docs/manual/extensions/notification-center.de.md
> +Last not least magst du vielleicht den Benutzer über die erfolgreiche Aktivierung der angeforderten Newsletter mittels einer Benachrichtigung informieren, die du im Modul `Newsletter aktivieren (Noti
```suggestion
Zu gu­ter Letzt magst du vielleicht den Benutzer über die erfolgreiche Aktivierung der angeforderten Newsletter mittels einer Benachrichtigung informieren, die du im Modul `Newsletter aktivieren (Notification Center)` einstellst.
```

2020-06-22 13:27 UTC, netzarbeiter commented on docs/manual/extensions/notification-center.de.md
> +Da dir das Notification Center die Möglichkeit bietet flexible Benachrichtigungen einzustellen, kannst du Benachrichtigungen in BCC z.B. an ein Email-Archiv adressieren, z.B. zu Nachweiszwecken.
```suggestion
Da dir das Notification Center die Möglichkeit bietet flexible Benachrichtigungen einzustellen, kannst du Benachrichtigungen in `BCC` z. B. zu Nachweiszwecken an ein E-Mail-Archiv adressieren.    
```

2020-06-22 13:27 UTC, netzarbeiter commented on docs/manual/extensions/notification-center.de.md
> +Es gelten die gleichen Optionen wie bei den Contao Modulen mit wenigen Unterschieden.
```suggestion
Es gelten die gleichen Optionen wie bei den Contao-Modulen mit wenigen Unterschieden.
```

2020-06-22 13:27 UTC, netzarbeiter commented on docs/manual/extensions/notification-center.de.md
> +Das Feld "Eigener Text" ist nicht mehr verfügbar.
```suggestion
Das Feld »Eigener Text« ist nicht mehr verfügbar. 
```

2020-06-22 13:27 UTC, netzarbeiter commented on docs/manual/extensions/notification-center.de.md
> +Beim Modul `Newsletter aktivieren (Notification Center)` benötigst du die Felder `Verteiler`und `Verteilermenü ausblenden` nicht, da durch die Dunkelverarbeitung keine Benutzereingabe während der La
```suggestion
Beim Modul `Newsletter aktivieren (Notification Center)` benötigst du die Felder `Verteiler` und `Verteilermenü ausblenden` nicht, da durch die Dunkelverarbeitung keine Benutzereingabe während der Laufzeit möglich und auch nicht notwendig sind.
```

2020-06-22 13:27 UTC, netzarbeiter commented on docs/manual/extensions/notification-center.de.md
> +Beim Modul `Newsletter aktivieren (Notification Center)` benötigst du die Felder `Verteiler`und `Verteilermenü ausblenden` nicht, da durch die Dunkelverarbeitung keine Benutzereingabe während der La
Was ist eine «Dunkelverarbeitung»?

2020-06-22 14:26 UTC, Ernestopheles commented on docs/manual/extensions/notification-center.de.md
> +Beim Modul `Newsletter aktivieren (Notification Center)` benötigst du die Felder `Verteiler`und `Verteilermenü ausblenden` nicht, da durch die Dunkelverarbeitung keine Benutzereingabe während der La
Dunkelverarbeitung = Im Hintergrund, ohne Benutzer-Interaktion und ohne GUI

Das vermutet man erst mal nicht, da ja Optionen anwählbar sind, die auf eine Bildschirmausgabe schließen lassen (Verteilermenü anzeigen). Deshalb dachte ich auch lange, dass das Aktivieren Modul ein **Dialog** zur Aktivierung deaktivierter Abonnements ist und etwas Zusätzliches ist, was beim Abonnement aber gar nicht benötigt wird. Zumal bei den "normalen" Contao Modulen es auch kein separates Aktivieren Modul gibt.

2020-06-22 16:07 UTC, netzarbeiter commented
Ich finde es super, dass du einen PR für die Erweiterung Notification Center eingereicht hast. Nach reiflicher Überlegung bin ich aber zur Ansicht gekommen, dass wenn wir über Erweiterungen schreiben, wir nicht nur einzelne Aspekt herausnehmen sollten. Kannst du deinen PR so erweitern, dass das NC als ganzes vorgestellt wird:

- Was ist das NC
- Was kann das NC
- Was ist ein Gateway und wie richte ich ihn ein
- Was sind Benachrichtigungen
- Wie lege ich eine neue Benachrichtigung an und was gilt es dabei zu beachten

Da das NC ursprünglich für Isotope eCommerce entwickelt wurde, findet sich auch Informationen im [Isotope-Handbuch](https://isotopeecommerce.org/de/handbuch/v/2.6/r/benachrichtigszentrum.html), gerne kannst du diese Texte verwenden und/oder ergänzen.

Vielen Dank.

2020-06-30 20:54 UTC, Ernestopheles commented
Mir war es wichtig, dass der Punkt, den ich weder in der Dokumentation noch im Lehrgang der academy finden konnte, irgendwo beschrieben wird. Das hätte mir sehr viel Zeit und Arbeit erspart... Ich verstehe, dass du lieber eine vollständige Doku hättest, aber warum verweisen wir nicht einfach dazu auf das Isotope Handbuch oder vielleicht würde Christian ein Video beisteuern, dann hätten wir es.  Ehrlich gesagt bin ich nicht so begeistert wie mit meinen PR im allgemeinen umgegangen wird. Einmal passt dieses nicht, dann das nicht.

2020-07-01 06:08 UTC, netzarbeiter commented
Hallo Ernst, es tut mir leid, dass du von unserem Umgang mit deinen PR enttäuscht bist. Vielleicht hat es damit zu tun, dass deine Beiträge immer sehr spezifisch auf deine Probleme eingehen und auch nur diese behandeln. Versuche doch mehr für die Allgemeinheit zu schreiben.

2020-07-21 10:19 UTC, m-vo commented
> Ehrlich gesagt bin ich nicht so begeistert wie mit meinen PR im allgemeinen umgegangen wird. Einmal passt dieses nicht, dann das nicht.

@Ernestopheles Nimm die Reviews nicht persönlich. :slightly_smiling_face: Wir bauen gemeinsam ein großes Projekt und versuchen ein bestmögliches Endergebnis zu schaffen. Das geht nie ohne Hin- und Her und auch nie ohne einen vermeintlich unnötigen Mehraufwand. Vermeintlich, weil: jeder Input hat Potential zum Entdecken und Lernen neuer Aspekte. Die Change Requests und Anmerkungen sind berechtigt und harmlos.

2020-07-21 10:23 UTC, Ernestopheles commented
OK, ich werde die Doku zusammenstellen, wird aber etwas dauern.
Am Dienstag, den 21.07.2020, 03:20 -0700 schrieb M. Vondano:
> > Ehrlich gesagt bin ich nicht so begeistert wie mit meinen PR im
> > allgemeinen umgegangen wird. Einmal passt dieses nicht, dann das
> > nicht.
> >
>
> @Ernestopheles Nimm die Reviews nicht persönlich. 🙂 Wir bauen
> gemeinsam ein großes Projekt und versuchen ein bestmögliches
> Endergebnis zu schaffen. Das geht nie ohne Hin- und Her und auch nie
> ohne einen vermeintlich unnötigen Mehraufwand. Vermeintlich, weil:
> jeder Input hat Potential zum Entdecken und Lernen neuer Aspekte. Die
> Change Requests und Anmerkungen sind berechtigt und harmlos.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-30 14:20 UTC, netzarbeiter commented
Ich schliesse diesen PR vorläufig.

2020-10-30 14:20 UTC, closed without merging