Added a link to PHP security note
contao/docs pull request #451
Opened 2020-06-24 11:42 UTC by Toflar

2020-06-24 12:07 UTC, fritzmg requested changes
The CSS of notices of the theme is very limited currently. It only applies to one `<p>` tag. Thus you will need to combine it to one paragraph.

2020-06-24 12:20 UTC, Toflar commented
Done

2020-06-29 14:26 UTC, fritzmg approved these changes

2020-06-29 14:29 UTC, merged

2020-06-29 14:29 UTC, netzarbeiter commented
Thank you @Toflar