Foundation for HTTP Caching in Contao
contao/docs pull request #487
Opened 2020-07-24 15:17 UTC by Toflar

Let's go!

2020-07-25 09:17 UTC, netzarbeiter requested changes
Wow, thank you very much.

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Contao baut dafür auf die Schultern von Giganten: dem Rückgrat des Internets, dem Hypertext Transfer Protocol (HTTP).
```suggestion
Contao baut dafür auf den Schultern der Giganten: dem Rückgrat des Internets, dem Hypertext Transfer Protocol (HTTP).
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Daher wurde darauf verzichtet, die Funktionsweise des Cachings für die älteren Versionen noch zu dokumentieren.
```suggestion
Daher wurde darauf verzichtet, die Funktionsweise des Cachings für die älteren Versionen zu dokumentieren.
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +zu Caching von HTTP Antworten gemacht haben?
```suggestion
zu Caching von HTTP-Antworten gemacht haben?
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Back to the basics, also. Zum Verständnis wie HTTP Caching in Contao konfiguriert werden kann, sollten wir uns kurz
```suggestion
Back to the basics, also. Zum Verständnis wie HTTP-Caching in Contao konfiguriert werden kann, sollten wir uns kurz 
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Diese Proxies können beliebige Aufgaben übernehmen, dazu gehören u.a.:
```suggestion
Diese Proxies können beliebige Aufgaben übernehmen, dazu gehören u. a.:
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +können, lässt sich jede HTTP-Anfrage und jede HTTP-Antwort mit Metadaten ausstatten. Diese sog. "HTTP-Header" sind
```suggestion
können, lässt sich jede HTTP-Anfrage und jede HTTP-Antwort mit Metadaten ausstatten. Diese sog. »HTTP-Header« sind
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +`www.contao.org`. Die Kommunikation zwischen Client und Server findet ja bekanntlich via IP statt und ein Server kann
```suggestion
`www.contao.org`. Die Kommunikation zwischen Client und Server findet via IP statt und ein Server kann
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +## Die HTTP-Caching Header
Konnte dazu keine Empfehlung finden, würde aber «HTTP-Caching-Header» bevorzugen.

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +dieser Dokumentation deutlich sprengen. Das Thema ist ausserdem bereits u.a. [bei MDN äusserst gut dokumentiert][mdn-caching],
```suggestion
dieser Dokumentation deutlich sprengen. Das Thema ist ausserdem bereits u. a. [bei MDN äusserst gut dokumentiert][mdn-caching],
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Den regulären Anwender von Contao interessiert vor allem der `Cache-Control` Header und dabei die wichtigsten drei
```suggestion
Den regulären Anwender von Contao interessiert vor allem der `Cache-Control`-Header und dabei die wichtigsten drei
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  teilen. Man spricht deshalb auch von einem geteilten Cache, dem «Shared Cache».
```suggestion
  teilen. Man spricht deshalb auch von einem geteilten Cache, dem »Shared Cache«.
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +| HTTP Header                        | Interpretation                                                                                                                                    |
```suggestion
| HTTP-Header                        | Interpretation                                                                                                                                    |
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +![Caching Einstellungsmöglichkeiten im Contao Backend](/de/performance/images/de/cache-einstellungen.png?classes=shadow)
```suggestion
![Caching-Einstellungsmöglichkeiten im Contao Backend](/de/performance/images/de/cache-einstellungen.png?classes=shadow)
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Die Contao Managed Edition wird mit einem Caching Proxy ausgeliefert, der ebenfalls in PHP geschrieben ist und direkt
Contao Managed Edition ist nach meinen [Recherchen](https://github.com/contao/managed-edition) die offzielle Schreibweise. Soll ich die Schreibweise in diesem [Blog-Beitrag](https://contao.org/de/news/release-der-contao-managed-edition.html) von dir übernehmen?

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +unseren Caching-Proxy geschickt und entsprechend den HTTP Headern im Cache abgelegt oder eben nicht.
```suggestion
unseren Caching-Proxy geschickt und entsprechend den HTTP-Headern im Cache abgelegt oder eben nicht.
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +auf den Headern der HTTP Requests und Responses die er vom Client bzw. von Contao bekommt.
```suggestion
auf den Headern der HTTP-Requests und -Responses die er vom Client bzw. von Contao bekommt.
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Gut zu wissen für dich: Welche Einstellungen auch immer du in den Seiten vorgenommen hast, Contao befolgt die HTTP
```suggestion
Gut zu wissen für dich: Welche Einstellungen auch immer du in den Seiten vorgenommen hast, Contao befolgt die HTTP-
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +* Der HTTP Statuscode muss grundsätzlich `200 OK`, `301 Permanent Redirect` oder `404 Not Found` lauten
```suggestion
* Der HTTP-Statuscode muss grundsätzlich `200 OK`, `301 Permanent Redirect` oder `404 Not Found` lauten
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Im Falle des mitgelieferten Contao Cache-Proxy's könnt ihr das relativ einfach überprüfen. Alle Antworten von Contao
Cache-Proxy's oder Cache-Proxies?

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  kann gecached werden und wir entsprechend abgelegt.
```suggestion
  kann gecached werden und wird entsprechend abgelegt.
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  `Age` HTTP Header. Er gibt dir an, wie viele Sekunden der Cache-Eintrag bereits existiert. Ein `Age: 60` bedeutet also,
```suggestion
  `Age` HTTP-Header. Er gibt dir an, wie viele Sekunden der Cache-Eintrag bereits existiert. Ein `Age: 60` bedeutet also,
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Wie wir gesehen haben, gibt es einige grundlegende Voraussetzungen, damit HTTP Caching funktionieren kann.
```suggestion
Wie wir gesehen haben, gibt es einige grundlegende Voraussetzungen, damit HTTP-Caching funktionieren kann.
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +* Wenn die Anfrage einen `Authorization` HTTP Header enthält
```suggestion
* Wenn die Anfrage einen `Authorization`-HTTP-Header enthält
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Das wichtigste Kriterium kennen wir bereits: Den `Cache-Control: public` Response Header. Wenn dieser Header fehlt, dann
```suggestion
Das wichtigste Kriterium kennen wir bereits: Den `Cache-Control: public`-Response-Header. Wenn dieser Header fehlt, dann
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  Der `Authorization` Header enthält gemäss Standard Authentifizierungsdetails. Für Contao bedeutet das daher, dass ggf.
```suggestion
  Der `Authorization`-Header enthält gemäss Standard Authentifizierungsdetails. Für Contao bedeutet das daher, dass ggf.
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  Contao hier `Cache-Control: private`. Contao teilt dir das auch mit: Der `Contao-Response-Private-Reason` Header
```suggestion
  Contao hier `Cache-Control: private`. Contao teilt dir das auch mit: Der `Contao-Response-Private-Reason`-Header
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  der Request einen `Authorization` Header enthält und somit der Cache immer deaktiviert wird. Bedenke das, wenn du
```suggestion
  der Request einen `Authorization`-Header enthält und somit der Cache immer deaktiviert wird. Bedenke das, wenn du
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +* Wenn die Anfrage ein PHP-Session Cookie enthält oder die Antwort es setzt
```suggestion
* Wenn die Anfrage ein PHP-Session-Cookie enthält oder die Antwort es setzt
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  im Frontend einloggt. In diesem Fall werden alle Antworten immer `private` und der `Contao-Response-Private-Reason`
```suggestion
  im Frontend einloggt. In diesem Fall werden alle Antworten immer `private` und der `Contao-Response-Private-Reason`-
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  aktuelle Antwort enthält also potenziell bereits persönliche Daten. Der `Contao-Response-Private-Reason` Header
```suggestion
  aktuelle Antwort enthält also potenziell bereits persönliche Daten. Der `Contao-Response-Private-Reason`-Header
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  den Weg zum Cache Proxy findet.
```suggestion
  den Weg zum Cache-Proxy findet.
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  Die Liste ist ziemlich lang und der aufmerksame Leser hat jetzt schon einen grundsätzlichen Unterschied zwischen z.B.
```suggestion
  Die Liste ist ziemlich lang und der aufmerksame Leser hat jetzt schon einen grundsätzlichen Unterschied zwischen z. B. 
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  dem zuvor erwähnten PHP-Session Cookie und z.B. dem `_ga_*` Cookie entdeckt. Denn eines davon ist wirklich relevant für
```suggestion
  dem zuvor erwähnten PHP-Session-Cookie und z. B. dem `_ga_*` Cookie entdeckt. Denn eines davon ist wirklich relevant für
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  liefern, denn dieses Cookie generiert keinen persönlichen Inhalt. Ein schlauer Cache Proxy könnte also nur die
```suggestion
  liefern, denn dieses Cookie generiert keinen persönlichen Inhalt. Ein schlauer Cache-Proxy könnte also nur die
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  irrelevanten Cookies innerhalb des Contao Cache Proxys. Diese werden vor dem Cache-Lookup vom Request entfernt
```suggestion
  irrelevanten Cookies innerhalb des Contao Cache-Proxies. Diese werden vor dem Cache-Lookup vom Request entfernt
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  TODO: Soll das hier überhaupt erwähnt werden? Irgendwo muss es ja auch für Nicht-Entwickler stehen.
Ja, gerne.

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +  Im Falle von Cookies, enthält der `Contao-Response-Private-Reason` Header `request-cookies` mit einer Liste aller
```suggestion
  Im Falle von Cookies, enthält der `Contao-Response-Private-Reason`-Header `request-cookies` mit einer Liste aller
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +{{% expand "Heisst das, die RememberMe-Funktion deaktiviert den Cache für einen Besucher komplett?" %}}
```suggestion
{{% expand "Heisst das, die Remember-Me-Funktion deaktiviert den Cache für einen Besucher komplett?" %}}
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Ja. Die Funktion von RememberMe ist, einen Besucher beim Aufruf egal welcher URL automatisch einzuloggen, sofern
```suggestion
Ja. Die Funktion von Remember-Me ist, einen Besucher beim Aufruf egal welcher URL automatisch einzuloggen, sofern
```

2020-07-25 09:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +der CookieBar kann man auch mit JavaScript dynamisch in den DOM einfügen lassen, wenn der entsprechende Key noch nicht
```suggestion
der Cookie-Bar kann man auch mit JavaScript dynamisch in den DOM einfügen lassen, wenn der entsprechende Key noch nicht
```

2020-07-25 18:33 UTC, fritzmg requested changes
Great work!

Btw. I personally would be interested in more information on how to use Varnish as the proxy instead of the built-in one ;)

2020-07-25 18:33 UTC, fritzmg commented on docs/manual/performance/http-caching.de.md
> +Es gibt eine Reihe an relevanten HTTP-Headern die relevant für HTTP-Caching sind. Sie alle zu erklären würde den Rahmen
```suggestion
Es gibt eine Reihe an HTTP-Headern die relevant für HTTP-Caching sind. Sie alle zu erklären würde den Rahmen
```

2020-07-25 18:33 UTC, fritzmg commented on docs/manual/performance/http-caching.de.md
> +  * Wie wär's mit Cloudflare's `__cfduid` Cookie?
```suggestion
  * Cloudflare's `__cfduid` Cookie
```
I'd stay a little more matter-of-factly ;) @netzarbeiter wdyt?

2020-07-27 12:34 UTC, Toflar commented on docs/manual/performance/http-caching.de.md
> +Contao baut dafür auf die Schultern von Giganten: dem Rückgrat des Internets, dem Hypertext Transfer Protocol (HTTP).
Das sehe ich anders. Ich baue auf etwas, auf die Schultern von Giganten.

2020-07-27 12:35 UTC, Toflar commented on docs/manual/performance/http-caching.de.md
> +Die Contao Managed Edition wird mit einem Caching Proxy ausgeliefert, der ebenfalls in PHP geschrieben ist und direkt
Darfst du gerne machen :)

2020-07-27 12:36 UTC, Toflar commented on docs/manual/performance/http-caching.de.md
> +Im Falle des mitgelieferten Contao Cache-Proxy's könnt ihr das relativ einfach überprüfen. Alle Antworten von Contao
Das ist korrekt so. Genitiv. Im Falle des Proxys bzw. Proxy's? Auf jeden Fall nicht `Proxies`, das ist die Mehrzahl.

2020-07-27 12:37 UTC, Toflar commented on docs/manual/performance/http-caching.de.md
> +  irrelevanten Cookies innerhalb des Contao Cache Proxys. Diese werden vor dem Cache-Lookup vom Request entfernt
Das ist falsch, siehe Kommentar weiter oben. Es ist nicht Mehrzahl sondern Genitiv.

2020-07-27 12:42 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Die Contao Managed Edition wird mit einem Caching Proxy ausgeliefert, der ebenfalls in PHP geschrieben ist und direkt
Erledigt

2020-07-27 12:48 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Contao baut dafür auf die Schultern von Giganten: dem Rückgrat des Internets, dem Hypertext Transfer Protocol (HTTP).
Ich «stolpere» jeweils beim Lesen dieses Satzes.

Contao nutz dafür Hypertext Transfer Protocol (HTTP), das Rückgrat des Internets.

2020-07-29 12:11 UTC, rabauss commented on docs/manual/performance/http-caching.de.md
> +dieser Dokumentation deutlich sprengen. Das Thema ist ausserdem bereits u. a. [bei MDN äusserst gut dokumentiert][mdn-caching],
`außerdem`

2020-07-29 12:11 UTC, rabauss commented on docs/manual/performance/http-caching.de.md
> +vor Contao sitzt. Das heisst, jede Antwort die Contao generiert, wird vor der Auslieferung an den Client durch
heisst = heißt -- ich glaub ich höre jetzt auf  `ß` für `ss` zu empfehlen - das tritt noch ein paar mal auf ;-)

2020-07-29 12:11 UTC, rabauss commented on docs/manual/performance/http-caching.de.md
> +auf den Headern der HTTP-Requests und -Responses die er vom Client bzw. von Contao bekommt.
`, die er vom Client...`

2020-07-29 12:11 UTC, rabauss commented on docs/manual/performance/http-caching.de.md
> +Im Falle des mitgelieferten Contao Cache-Proxy's könnt ihr das relativ einfach überprüfen. Alle Antworten von Contao
Ich würde aber sagen `Proxys` - ein Apostroph würde eine Buchstaben-Auslassung bedeuten

2020-07-29 12:11 UTC, rabauss commented on docs/manual/performance/http-caching.de.md
> +werden dann nämlich mit einem `Contao-Cache` Header ausgestattet welcher grundsätzlich drei Werte annehmen kann:
`, welcher...`

2020-07-29 12:11 UTC, rabauss commented on docs/manual/performance/http-caching.de.md
> +{{% expand "Meine Erweiterung speichert aber in einem Cookie ob die Cookie-Bar noch angezeigt werden soll, dann ist der Cache ja auch immer deaktiviert?" %}}
`, ob die Cookie-Bar`

2020-07-29 12:19 UTC, Toflar commented
@rabauss könntest du die Vorschläge nicht so machen, dass ich sie direkt übernehmen kann? :D Siehe Punkt 6: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request

@fritzmg @netzarbeiter schreiben wir mit `ß` bzw. `ss`. Mein Problem ist, dass ich die Regeln dafür noch nicht mal kenne 🙈

2020-07-29 12:25 UTC, netzarbeiter commented
Ich schreibe eigentlich nur mit `ss` weil ich die Regeln auch noch nicht kenne.

2020-07-29 12:31 UTC, Toflar commented
Gut, ich werd's auch dabei belassen. Es gibt ja dann etliches in der Doku, das mit `ss` statt `ß` geschrieben ist. Wem das wichtig ist, soll es in regelmässigen Abständen per PR korrigieren. Mich stört's überhaupt nicht beim Lesen, ich kann's halt einfach nicht schreiben.

2020-07-29 12:39 UTC, Toflar reviewed
@rabauss @netzarbeiter your comments have all been addressed in the latest commits.

I need to document the env vars now and then we're good to go :)

2020-07-29 12:39 UTC, Toflar commented on docs/manual/performance/http-caching.de.md
> +Contao baut dafür auf die Schultern von Giganten: dem Rückgrat des Internets, dem Hypertext Transfer Protocol (HTTP).
Verbessert in 9b2bfb5443c58d9d5f56c1c15069e5b68f62e289.

2020-07-29 13:07 UTC, Toflar commented
Done, this is ready for a final review from my side 🎉

2020-07-29 14:17 UTC, netzarbeiter requested changes

2020-07-29 14:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Die nachfolgenden Umgebungsvariabeln erlauben dir, den Cache-Proxy weiter zu optimieren:
```suggestion
Die nachfolgenden Umgebungsvariablen erlauben dir, den Cache-Proxy weiter zu optimieren:
```

2020-07-29 14:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +auch die Deativierung des Cachings zur Folge haben.
```suggestion
auch die Deaktivierung des Cachings zur Folge haben.
```

2020-07-29 14:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +3. Das Trusted Device Cookie für vertrauten Geräten bei aktivierter Zweifaktorauthentifizierung.
```suggestion
3. Das Trusted Device Cookie für vertrauten Geräten bei aktivierter Zwei-Faktor-Authentifizierung.
```

2020-07-29 14:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +lautet. Ausserdem ist der Name des CSRF-Cookies aus sicherheitsgründen für `http` und `https` unterschiedlich. Solltest
```suggestion
lautet. Ausserdem ist der Name des CSRF-Cookies aus Sicherheitsgründen für `http` und `https` unterschiedlich. Solltest
```

2020-07-29 14:17 UTC, netzarbeiter commented on docs/manual/performance/http-caching.de.md
> +Denn ansonsten rennen wir wiederum in das Problem, dass du viele Cache-Einträge generiert werden.
```suggestion
Denn ansonsten rennen wir wiederum in das Problem, dass du viele Cache-Einträge generieren wirst.
```

2020-07-29 14:53 UTC, Toflar commented on docs/manual/performance/http-caching.de.md
> +Denn ansonsten rennen wir wiederum in das Problem, dass du viele Cache-Einträge generiert werden.
```suggestion
Denn ansonsten rennen wir wiederum in das Problem, dass zu viele Cache-Einträge generiert werden.
```

So hätte das lauten sollen ;)

2020-07-29 14:57 UTC, netzarbeiter approved these changes

2020-07-30 07:03 UTC, fritzmg approved these changes

2020-07-30 07:06 UTC, merged

2020-07-30 07:07 UTC, Toflar commented
I did it 🕺

2020-07-30 08:27 UTC, rabauss commented
Sorry, ich habe bei Github angefangen drüber zu lesen und dann stand da nur die Kommentarfunktion zur Verfügung - beim nächsten Mal mach ich das besser ;-)