EN Form Generator Guide Cleanup
contao/docs pull request #524
Opened 2020-08-06 16:50 UTC by blairwinans

My only question is how we are handling updating the links, as I left a lot of them intact but going to their /de/ counterparts. Let me know if there is anything I should do with those, along with any issues you may see. If I can get into a rhythm with these my hope is to help with a bunch. :) Thank you!

2020-08-18 06:46 UTC, netzarbeiter requested changes
Thank you, Blair.

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/_index.en.md
>  title: 'Form Generator'
```suggestion
title: "Form Generator"
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/_index.en.md
> +description: 'The Contao form generator helps you create forms by abstracting both the process of code generation and the complexity of validating the user input.'
```suggestion
description: "The Contao form generator helps you create forms by abstracting both the process of code generation and the complexity of validating the user input."
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/_index.en.md
>      - /en/form-generator/_index/
```suggestion
    - /en/form-generator/
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/create-a-search-form.en.md
>  title: 'Create a search form'
```suggestion
title: "Create a search form"
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/create-a-search-form.en.md
> +description: 'You can use the form generator to create your own search form and include it in the header of your website, as an example.'
```suggestion
description: "You can use the form generator to create your own search form and include it in the header of your website, as an example."
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/create-a-search-form.en.md
> +As already mentioned in the section [My Search Forms](../../modulverwaltung/website-suche/#eigene-suchformulare), you
```suggestion
As already mentioned in the section [My Search Forms](../../module-management/website-search/#own-search-forms), you 
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/create-a-search-form.en.md
> +1. Open the form generator, and create[ a new form](../../formulargenerator/formulare/#formular-konfiguration). Specify
```suggestion
1. Open the form generator, and create [a new form](../../form-generator/forms/#form-configuration). Specify 
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/create-a-search-form.en.md
> +2. Add a [text field](../../formulargenerator/formularfelder/#textfeld) to the form, and enter the field `keywords` name.
```suggestion
2. Add a [text field](../../form-generator/form-fields/#text-field) to the form, and enter the field `keywords` name. 
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/create-a-search-form.en.md
> +3. Optionally add a [radio button menu](../../formulargenerator/formularfelder/#radio-button-menue) to the form if you
```suggestion
3. Optionally add a [radio button menu](../../form-generator/form-fields/#radio-button-menu) to the form if you 
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/create-a-search-form.en.md
>  4. Add a [submit button](../../formulargenerator/formularfelder/#absendefeld) to the form.
```suggestion
4. Add a [submit button](../../form-generator/form-fields/#submit-field) to the form.
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/form-fields.en.md
>  title: 'Form fields'
```suggestion
title: "Form fields"
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/form-fields.en.md
> +description: 'Similar to articles and content elements, forms will contain a separate element for each form field, which
```suggestion
description: "Similar to articles and content elements, forms will contain a separate element for each form field, which 
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/form-fields.en.md
> +is specifically configured to meet the requirements for that field.'
```suggestion
is specifically configured to meet the requirements for that field."
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/form-fields.en.md
> +`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number[ (see backend keyboard shortcuts](../../administrationsbereich/backend-tastaturkuerzel/)).
```suggestion
`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number ([see backend keyboard shortcuts](../../administrationsbereich/keyboard-shortcuts/)).
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/form-fields.en.md
> +`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number[ (see backend keyboard shortcuts](../../administrationsbereich/backend-tastaturkuerzel/)).
```suggestion
`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number ([see backend keyboard shortcuts](../../administrationsbereich/keyboard-shortcuts/)).
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/form-fields.en.md
> +`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number[ (see backend keyboard shortcuts](../../administrationsbereich/backend-tastaturkuerzel/)).
```suggestion
`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number ([see backend keyboard shortcuts](../../administrationsbereich/keyboard-shortcuts/)).
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/form-fields.en.md
> +`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number[ (see backend keyboard shortcuts](../../administrationsbereich/backend-tastaturkuerzel/)).
```suggestion
`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number ([see backend keyboard shortcuts](../../administrationsbereich/keyboard-shortcuts/)).
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/form-fields.en.md
> +The form field `Security question` adds a [CAPTCHA](https://de.wikipedia.org/wiki/Captcha) to the form.
```suggestion
The form field `Security question` adds a [CAPTCHA](https://en.wikipedia.org/wiki/CAPTCHA) to the form.
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/form-fields.en.md
> +`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number[ (see backend keyboard shortcuts](../../administrationsbereich/backend-tastaturkuerzel/)).
```suggestion
`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number ([see backend keyboard shortcuts](../../administrationsbereich/keyboard-shortcuts/)).
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/form-fields.en.md
> +`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number[ (see backend keyboard shortcuts](../../administrationsbereich/backend-tastaturkuerzel/)).
```suggestion
`[Alt]` or `[Strg]` key in connection with the shortcut key, e.g. a number ([see backend keyboard shortcuts](../../administrationsbereich/keyboard-shortcuts/)).
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/forms.en.md
>  Without specifying a separate SMTP server, the data is [sent](https://de.wikipedia.org/wiki/Sendmail) via [sendmail](https://de.wikipedia.org/wiki/Sendmail), which can lead to problems.
```suggestion
Without specifying a separate SMTP server, the data is sent via [sendmail](https://en.wikipedia.org/wiki/Sendmail), which can lead to problems.
```

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/forms.en.md
>  weight: 10
title: "Forms"
description: "With the form generator you can create forms and either send their data by e-mail or write them into the database."

2020-08-18 06:46 UTC, netzarbeiter commented on docs/manual/form-generator/form-fields.en.md
>  <div class="widget widget-text … mandatory">
<span class="invisible">Mandatory field </span>…<span class="mandatory">*</span>

2020-08-26 08:38 UTC, fritzmg approved these changes
looks good to me 👍

2020-08-26 08:40 UTC, netzarbeiter approved these changes

2020-08-26 08:46 UTC, fritzmg commented
@blairwinans do you need help with resolving the conflicts? Also could you may be enable "allow edits from maintainers" for this PR? It seems to be disabled.

2020-08-28 00:36 UTC, blairwinans commented
@fritzmg Sorry! Had turned off my GitHub notifications. That is not an option I see, probably because I forked it into our company repo and not my personal one. Sorry! Should be better now? Next time I'll fork on my personal account.

2020-08-28 04:25 UTC, merged

2020-08-28 04:25 UTC, netzarbeiter commented
Thank you very much, Blair.