Update system-requirements.de.md
contao/docs pull request #579
Opened 2020-10-11 08:57 UTC by tschero

Mal ein erster Versuch an der Doku mitzuarbeiten.

2020-10-11 10:39 UTC, fritzmg commented
Danke @tschero :). Allerdings stimmt diese Änderung nicht. Die minimale PHP Version ist nach wie vor 7.2. Warum wolltest du es auf 7.4 setzen?

2020-10-12 14:50 UTC, fritzmg requested changes
Danke @tschero :). Allerdings stimmt diese Änderung nicht. Die minimale PHP Version ist nach wie vor 7.2. Warum wolltest du es auf 7.4 setzen?

2020-10-12 19:06 UTC, tschero commented
Moin Fritz,
ich habe mehrere Installationen von Contao 4.9.5 auf 4.9.8 aktualisiert.
Weder bei IONOS noch bei NetCup liefen die Seiten mit PHP 7.3.
Das Verhalten konnte ich reproduzieren.
Ein downgrade funktionierte dann wieder.

http://adobe-captivate-forum.forumprofi.de/


> Gesendet: Montag, 12. Oktober 2020 um 16:50 Uhr
> Von: "Fritz Michael Gschwantner" <notifications@github.com>
> An: "contao/docs" <docs@noreply.github.com>
> Cc: "Marco Pracht" <marco.pracht@gmx.de>, "Mention" <mention@noreply.github.com>
> Betreff: Re: [contao/docs] Update system-requirements.de.md (#579)
>
> @fritzmg requested changes on this pull request.
> 
> Danke @tschero :). Allerdings stimmt diese Änderung nicht. Die minimale PHP Version ist nach wie vor 7.2. Warum wolltest du es auf 7.4 setzen?
> 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/contao/docs/pull/579#pullrequestreview-506689106

2020-10-12 19:59 UTC, fritzmg commented
Ein allgemeines Problem mit PHP 7.2 wäre nicht bekannt. Wie gesagt ist Contao 4.9 und 4.10 grundsätzlich mit PHP 7.2 kompatibel. Wenn du ein spezifisches Problem hattest, poste das evt. im Contao Community Forum.

2020-10-12 19:59 UTC, closed without merging