Update CM User FAQ
contao/docs pull request #591
Opened 2020-10-22 16:15 UTC by fkaminski

Because of https://community.contao.org/de/showthread.php?79186-2ter-Contao-Manager-Account:
Add info about how to create another secret CM user/password ...

2020-10-22 16:56 UTC, fritzmg requested changes

2020-10-22 16:56 UTC, fritzmg commented on docs/manual/installation/contao-manager.en.md
> +you could, for example, generate the necessary hash value.
```suggestion
The value for "password" must be encrypted. You can use services like [bcrypt-generator.com](https://bcrypt-generator.com/) 
for example in order to generate the necessary hashed value.
```

2020-10-23 09:03 UTC, fritzmg approved these changes

2020-10-23 09:09 UTC, netzarbeiter approved these changes
Thank you, Franko

2020-10-23 09:09 UTC, merged