Update update-contao.en.md
contao/docs pull request #602
Opened 2020-11-01 15:10 UTC by fiedsch

* add english traslation of #578
* revise the automatic translation

TODO:
* localised screen shots

2020-11-02 11:49 UTC, fkaminski commented
@fiedsch
Maybe you can add the following hints from @fritzmg  (which he had left in my PR):

_Generally I only noticed just now, that the commands use composer.phar. However, it is not explained that you first have to either download the latest composer.phar - or install it globally (and if you installed it globally, you can simply use composer, without prepending php - unless in specific circumstances)._

And maybe a add notice that this procedure basically also works for new installations also...

2020-11-02 12:27 UTC, fiedsch commented
@fkaminski Thanks. I will include that in my PR (and also the already published german version). 

My original intention was to explain that with

> Composer (wir gehen hier davon aus, dass du Composer in deinem Arbeitsverzeichnis installierst)

which would make `composer.phar` available in the working directory and the examples should work.

I suggest, I add a link to https://docs.contao.org/manual/de/installation/contao-installieren/#composer-installieren
(or https://docs.contao.org/manual/en/installation/install-contao/#install-composer respectively) to make that clearer.

@fritzmg what do you think?

2020-11-03 08:54 UTC, fritzmg commented
Yeah sounds good :)

2020-11-09 15:01 UTC, fiedsch commented
Updated PR. If we agree that this description is what we want, I'd
* create the english screenshots 
* update the german documentation accordingly

2020-11-09 20:36 UTC, fritzmg commented
_You don't have to_, but while you are at it, could you also review and overhaul the rest of the content of these articles, since they are still only machine translated? 😬 😁

2020-11-09 20:38 UTC, fritzmg commented
> If we agree that this description is what we want

Imho description looks good :)

2020-11-10 00:16 UTC, xchs commented on docs/manual/installation/install-contao.en.md
> +You can either install composer [locally](https://getcomposer.org/doc/00-intro.md#locally)
```suggestion
You can either install Composer [locally](https://getcomposer.org/doc/00-intro.md#locally) 
```

2020-11-10 00:16 UTC, xchs commented on docs/manual/installation/install-contao.en.md
> + `composer.json`and `composer.lock` files are located). You would then call composer with `php composer.phar`.
```suggestion
 `composer.json`and `composer.lock` files are located). You would then call Composer with `php composer.phar`.
```

2020-11-10 00:16 UTC, xchs commented on docs/manual/installation/update-contao.en.md
> + To update Contao via the command line you need to have composer [installed](../install-contao/#install-composer).
```suggestion
 To update Contao via the command line you need to have Composer [installed](../install-contao/#install-composer). 
```

2020-11-10 00:16 UTC, xchs commented on docs/manual/installation/update-contao.en.md
> +- Composer (we assume here that you [install](../install-contao/#install-composer) composer globally)
```suggestion
- Composer (we assume here that you [install](../install-contao/#install-composer) Composer globally)
```

2020-11-10 07:10 UTC, fiedsch commented
thanks, @xchs!

@fritzmg:
> You don't have to, but while you are at it, could you also review and overhaul the rest of the content of these articles, since they are still only machine translated?

I suggest, I finish this PR (including the respective changes in the german version) and then work on the mashine translated texts in a different PR. Otherwise I fear, I‘m losing track.

2020-11-15 19:28 UTC, fiedsch commented
"finished" PR and removed draft status.

2020-11-16 08:09 UTC, netzarbeiter requested changes
Thank you, Andreas.

2020-11-16 08:09 UTC, netzarbeiter commented on docs/manual/installation/install-contao.de.md
> +Wenn du Composer lokal installierst, befindet sich die Datei `composer.phar` in deinem Arbeitsverzeichnis (d.h. dort, wo
```suggestion
Wenn du Composer lokal installierst, befindet sich die Datei `composer.phar` in deinem Arbeitsverzeichnis (d. h. dort, wo
```

2020-11-16 08:09 UTC, netzarbeiter commented on docs/manual/installation/install-contao.en.md
> +If you install locally, you will have a `composer.phar` file in your working directory (i.e. where your project's
Suggestion:
If you install Composer …
If you install it …

2020-11-16 08:09 UTC, netzarbeiter commented on docs/manual/installation/install-contao.en.md
> +If you install globally, you can use the `composer` command in any directory.
Suggestion:
If you install Composer …
If you install it …

2020-11-16 08:09 UTC, netzarbeiter commented on docs/manual/installation/update-contao.en.md
> +versions have been released in the meantime. An overview of all Contao versions is available on Wikipedia.
```suggestion
versions have been released in the meantime. An overview of all Contao versions is available on [Wikipedia](https://en.wikipedia.org/wiki/Contao#Versions).
```

2020-11-16 08:09 UTC, netzarbeiter commented on docs/manual/installation/update-contao.en.md
> +```bash
```suggestion

```bash
```

2020-11-16 08:09 UTC, netzarbeiter commented on docs/manual/installation/update-contao.en.md
> +Before doing so, make sure that the Composer Resolver Cloud is not used! You do not need it, because you you can provide
```suggestion
Before doing so, make sure that the Composer Resolver Cloud is not used! You don't need it, because you can provide 
```

2020-11-16 08:23 UTC, fiedsch commented
Thank you @netzarbeiter. I updated the PR.

2020-11-16 08:24 UTC, netzarbeiter approved these changes

2020-11-16 08:24 UTC, merged