Add page controllers and routing info
contao/docs pull request #604
Opened 2020-11-01 23:13 UTC by fritzmg

This adds documentation about the new page controllers and also adds more information about routing in general, i.e. Contao specific route attributes and how and why to use them and also a general guide on how to implement your own independent routes.

@aschempp As far as I know there is nothing place yet to make rendering a complete layout defined via the page layout of Contao for a custom page type implemented via page controllers, is that correct? You can enable `contentComposition` and then are able add articles and content elements in the back end for that page - but you would still have to render everything yourself.

@netzarbeiter I've marked this for the two month review :)

2020-11-05 11:01 UTC, aschempp requested changes
> @aschempp As far as I know there is nothing place yet to make rendering a complete layout defined via the page layout of Contao for a custom page type implemented via page controllers, is that correct? You can enable contentComposition and then are able add articles and content elements in the back end for that page - but you would still have to render everything yourself.

You don't render them yourself. You pass the `pageModel` to `PageRegular::renderPage`. However, this is currently "dangerous" because permissions will not be checked. See https://github.com/contao/contao/pull/2015/files#diff-84c54a7b63df1afc1990d4aea951a7a696d445b16a2c4937591831a96f5d1ea4R28 for an early draft.

2020-11-05 11:01 UTC, aschempp commented on docs/dev/framework/page-controllers.md
> +can also be registered via annotations. The following shows the most basic example:
```suggestion
can be registered via annotations. The following shows the most basic example:
```

2020-11-05 11:01 UTC, aschempp commented on docs/dev/framework/page-controllers.md
> +`contao.tag`.
```suggestion
`contao.page`.
```

2020-11-05 11:01 UTC, aschempp commented on docs/dev/framework/page-controllers.md
> +Now we are all set and can add this new page type in the site structure of the Contao
```suggestion
Now we are all set and can add this new page in the site structure of the Contao
```

please refrain from calling it `page type`, thats the _old term_. There are different types of pages, and there are different types of content elements or modules. But we never call them `content element type`.

2020-11-05 11:01 UTC, aschempp commented on docs/dev/framework/page-controllers.md
> +![Custom page type in the Contao back end](/framework/images/custom-page-type-back-end.png?classes=shadow)
I don't see that image in the pull request?

2020-11-05 11:01 UTC, aschempp commented on docs/dev/framework/page-controllers.md
> +annotation where in the latter case, the first parameter is the _path_ of the route.
👍 👍

2020-11-05 11:01 UTC, aschempp commented on docs/dev/framework/page-controllers.md
> +is defined in the back end.
add something like 

> => means the `alias` field should not be in the palette

2020-11-05 11:01 UTC, aschempp commented on docs/dev/framework/page-controllers.md
> +of the page will be `https://example.com/example/alias/foo/bar`.
what about the URL suffix?

2020-11-05 11:01 UTC, aschempp commented on docs/dev/framework/page-controllers.md
> +end URL will be `https://example.com/foo/bar.csv`.
> … even though the root page's url suffix might be `.html`

2020-11-05 11:01 UTC, aschempp commented on docs/dev/framework/page-controllers.md
> +then you need to enable this property on your page controller:
it's not specifically about articles, it is related to page layouts. _Content composition_ refers to layouting the page in the back end (including articles). For example, an RSS feed page type does not use content composition.

2020-11-05 11:01 UTC, aschempp commented on docs/dev/framework/routing.md
> +request handled by this route. As of Contao **4.9** there are two different special
which ones are for Contao 4.9?

2020-11-05 12:09 UTC, fritzmg commented
> You don't render them yourself. You pass the `pageModel` to `PageRegular::renderPage`. However, this is currently "dangerous" because permissions will not be checked. See https://github.com/contao/contao/pull/2015/files#diff-84c54a7b63df1afc1990d4aea951a7a696d445b16a2c4937591831a96f5d1ea4R28 for an early draft.

Hmm... should we even mention it then? Still seems rather involved.

2020-11-07 07:29 UTC, aschempp commented
mention page rendering or the page controllers at all?

2020-11-08 16:04 UTC, fritzmg commented on docs/dev/framework/page-controllers.md
> +![Custom page type in the Contao back end](/framework/images/custom-page-type-back-end.png?classes=shadow)
Yeah, forgot to create it :)

2020-11-08 16:19 UTC, fritzmg commented
> mention page rendering or the page controllers at all?

Mentioning how you would be able to render a page layout in your own page controller. Explaining everything that would be in the `AbstractPageController` from your PR would be too much.

2020-11-08 16:22 UTC, fritzmg commented on docs/dev/framework/page-controllers.md
> +![Custom page type in the Contao back end](/framework/images/custom-page-type-back-end.png?classes=shadow)
Oh actually it is in the PR.

2020-11-08 16:29 UTC, fritzmg commented on docs/dev/framework/page-controllers.md
> +then you need to enable this property on your page controller:
Ok, rephrased now.

2020-11-08 16:32 UTC, fritzmg commented on docs/dev/framework/routing.md
> +request handled by this route. As of Contao **4.9** there are two different special
Not sure why I phrased it this way. Both of them are available in Contao 4.4.

2020-11-08 17:44 UTC, aschempp commented
I think it really depends on the use case. I implemented similar controller stuff years ago in Contao <4.9, but simply because I knew my system does not need authentication or thelike. If the (page) controller is created for the app, I might control what's necessary. But it shouldn't be in a bundle just yet because people might expect certain behavior 🤷

2020-11-10 21:03 UTC, fritzmg commented
Ok, so the most basic example would be

```php
// src/Controller/Page/ExamplePageController.php
namespace App\Controller\Page;

use Contao\CoreBundle\ServiceAnnotation\Page;
use Contao\PageModel;
use Contao\PageRegular;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Page(contentComposition=true)
 */
class ExamplePageController
{
    public function __invoke(PageModel $pageModel): Response
    {
        // The legacy framework relies on the global $objPage variable
        global $objPage;
        $objPage = $pageModel;

        // Render the page using the PageRegular handler from the legacy framework
        return (new PageRegular())->getResponse($pageModel, true);
    }
}
```
However, doing just that is pretty nonsensical as you could simply use a regular page instead. So I'd like to show some use cases, but I am not actually sure what the use cases are. Can you provide some simplified real world examples?

2020-11-13 10:10 UTC, aschempp commented
In the current state (where there's no abstraction to render a layout), custom page controllers mostly make sense if you want to generate something else than a page. As an example, the news extension allows to define RSS feeds. Instead of the current configuration and writing the feed into a folder, the feed could be a page controller. For each feed, you would create a page in the tree and give it the alias of the feed path you want to have. The configuration of the feed would take place inside the page configuration. This would have the advantage of a feed being specific to a domain/root page, and you could use any page alias/folder alias you want to reach the news feed (even the same as the list page, with a different suffix).

2020-11-22 17:16 UTC, fritzmg commented
> However, this is currently "dangerous" because permissions will not be checked.

Btw. that applies to _all_ pages implemented as page controllers, not just the ones using content composition, does it not? If you implement a page via a page controller and then allow it to be restricted to a front end member group for example, you still need to make that check for yourself.

2020-11-22 17:25 UTC, fritzmg commented on docs/dev/framework/page-controllers.md
> +Now we are all set and can add this new page type in the site structure of the Contao
That's hard to do btw. There even is a `FilterPageTypeEvent` in the core now ;)

2020-11-22 17:29 UTC, fritzmg commented
I have added some additional notes on how or why to use page controllers. I also added the primitive example for pages with enabled content composition. This will be then later on changed for the upcoming Contao versions.

2020-11-22 17:32 UTC, merged