Wartungstemplate Guide
contao/docs pull request #655
Opened 2021-02-01 18:13 UTC by contaoacademy

2021-02-01 18:17 UTC, fritzmg requested changes

2021-02-01 18:17 UTC, fritzmg commented on docs/manual/guides/maintenance-template.de.md
> +Der Wartungsmodus lässt sich über den Menüpunkt Systemwartung aktivieren. Sobald du dich aus dem Backend abgemeldet hast und deine Website im Frontend aufrufst, sieht das dann so aus:
```suggestion

Der Wartungsmodus lässt sich über den Menüpunkt Systemwartung aktivieren. Sobald du dich aus dem Backend abgemeldet hast und deine Website im Frontend aufrufst, sieht das dann so aus:
```

2021-02-01 18:17 UTC, fritzmg commented on docs/manual/guides/maintenance-template.de.md
> +## Texte des Wartungstemplates anpassen
```suggestion

## Texte des Wartungstemplates anpassen
```

2021-02-01 18:17 UTC, fritzmg commented on docs/manual/guides/maintenance-template.de.md
> +Alternativ kann auch die PHP Notation verwendet werden. Dazu legst du eine exeption.php an, die dann ungefähr so aussieht:
```suggestion
Alternativ kann auch die PHP Notation verwendet werden. Dazu legst du eine exception.php an, die dann ungefähr so aussieht:
```

2021-02-01 18:17 UTC, fritzmg commented on docs/manual/guides/maintenance-template.de.md
> +Damit die neuen Texte nun sichtbar werden, muss der Produktion-Cache über den Contao Manager oder die Kommandozeile geleert werden.
```suggestion
Damit die neuen Texte nun sichtbar werden, muss der Produktions-Cache über den Contao Manager oder die Kommandozeile geleert werden.
```

2021-02-01 18:17 UTC, fritzmg commented on docs/manual/guides/maintenance-template.de.md
> +## Logo anpassen
```suggestion

## Logo anpassen
```

2021-02-01 18:17 UTC, fritzmg commented on docs/manual/guides/maintenance-template.de.md
> +```html
```suggestion

```html
```

2021-02-01 18:17 UTC, fritzmg commented on docs/manual/guides/maintenance-template.de.md
> +% trans_default_domain 'contao_exception' %}
```suggestion
{% trans_default_domain 'contao_exception' %}
```

2021-02-01 18:17 UTC, fritzmg commented on docs/manual/guides/maintenance-template.de.md
> +Anstatt nur einzelne Texte anzupassen, kannst du auch einfach das komplette Template `service_unavailable.html.twig` mit deinem eigenen HTML und CSS überschreiben.
```suggestion

## Komplettes Wartungstemplate überschreiben

Anstatt nur einzelne Texte anzupassen, kannst du auch einfach das komplette Template `service_unavailable.html.twig` mit deinem eigenen HTML und CSS überschreiben.
```

2021-02-06 12:24 UTC, contaoacademy commented
Muss ich hier noch was tun?

2021-02-06 14:53 UTC, fritzmg approved these changes
LGTM :)

PR will be merged by @netzarbeiter

2021-02-21 14:22 UTC, netzarbeiter approved these changes
Thank you, Christian

2021-02-21 14:23 UTC, merged