Update devilbox.de.md
contao/docs pull request #663
Opened 2021-02-17 02:07 UTC by Ernestopheles

Zumindest bei meinem Kubuntu 20.10 war docker-compose nicht vorinstalliert.

2021-02-17 05:15 UTC, fiedsch requested changes
```
sudo usermod -a -G docker $USER
```

2021-02-17 07:37 UTC, fkaminski commented
Hab kein Linux - Grundsätzlich wird halt aber immer eine docker Installation benötigt.
Der Befehl docker-compose ist ja nur ein Teil der Installation ...

2021-02-21 14:56 UTC, netzarbeiter commented
Ich setzte selber Docker nicht ein und kann deshalb nicht beurteilen, ob dieser PR veröffentlicht werden kann.

2021-02-21 20:16 UTC, fritzmg commented
Instead of mentioning only Docker Composer specifically, the introduction should just mention the basic requirements for running the Devilbox (i.e. having Docker and Docker Composer installed) and only link to https://devilbox.readthedocs.io/en/latest/getting-started/prerequisites.htm, if you require more information on how to install that. I'll provide an alternative PR for that.

2021-02-22 05:47 UTC, netzarbeiter commented
Vielen Dank, ich schliesse dieses Ticket und füge den Alternativvorschlag von Fritz ein.
https://github.com/contao/docs/pull/666

2021-02-22 05:47 UTC, closed without merging