Update Docker/Devilbox install options
contao/docs pull request #669
Opened 2021-02-24 16:10 UTC by fkaminski

As described on slack a few updates regarding Docker installation for Windows users

2021-02-24 16:16 UTC, fritzmg requested changes

2021-02-24 16:16 UTC, fritzmg commented on docs/manual/guides/local-installation/devilbox.de.md
> +»[Windows 10 Pro](https://docs.docker.com/docker-for-windows/install/)«, bereit.
This removes the notice about having to install Docker and Docker Compose and only mentions Windows.

2021-02-24 16:41 UTC, fkaminski commented
OK, i have now deposited the appropriate links in the original note ...

2021-02-25 07:24 UTC, fkaminski commented
Little more detail regarding Windows 10 and WSL 2

2021-03-07 11:16 UTC, fkaminski commented
After reviewing the PR is not really necessary.
Even the hints about uid/gid (with WSL 2) - These are not necessary - but also do not hurt ...
So i close this ...
Thanks

2021-03-07 11:16 UTC, closed without merging