Add OpenSearch Info
contao/docs pull request #691
Opened 2021-03-21 13:15 UTC by fkaminski

Because [everyone ](https://community.contao.org/de/showthread.php?80545-Die-Contao-Dokumentation-direkt-in-der-Browser-Suche-heranziehen#post541889)love this [feature](https://github.com/contao/docs/pull/689) ...

2021-03-21 18:10 UTC, fritzmg requested changes

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.de.md
> +einmalig die Dokumentation als zusätzliche Suchmaschiene in deinem Browser registrieren.
```suggestion
einmalig die Dokumentation als zusätzliche Suchmaschine in deinem Browser registrieren.
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.de.md
> +- Suchmaschiene: ``https://docs.contao.org/manual/``
```suggestion
- Suchmaschine: `https://docs.contao.org/manual/`
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.de.md
> +- In »Einstellungen/Suche«, einen Kürzel eingeben: z.B. ``@doc``
```suggestion
- In »Einstellungen/Suche«, einen Kürzel eingeben: z.B. `@doc`
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.de.md
> +- ``@docs inserttags``
```suggestion
- `@docs inserttags`
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.de.md
> +- URL mit %s statt der Suchanfrage: ``https://docs.contao.org/manual/de/?search=%s``
```suggestion
- URL mit %s statt der Suchanfrage: `https://docs.contao.org/manual/de/?search=%s`
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.de.md
> +- ``docs insterttags``
```suggestion
- `docs insterttags`
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.de.md
> +- Suchkürzel: z.B. ``docs`` (beliebig)
```suggestion
- Suchkürzel: z.B. `docs` (beliebig)
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.en.md
> -{{% /notice %}}
Please do not remove these lines.

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.en.md
> +- In "Settings/Search", enter an abbreviation: e.g. ``@doc``.
```suggestion
- In "Settings/Search", enter an abbreviation: e.g. `@doc`.
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.en.md
> +- ``@docs inserttags``
```suggestion
- `@docs inserttags`
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.en.md
> +- Search engine: ``https://docs.contao.org/manual/``
```suggestion
- Search engine: `https://docs.contao.org/manual/`
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.en.md
> +- Search abbreviation: e.g. ``docs`` (any)
```suggestion
- Search abbreviation: e.g. `docs` (any)
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.en.md
> +- URL with %s instead of the search query: ``https://docs.contao.org/manual/de/?search=%s``
```suggestion
- URL with %s instead of the search query: `https://docs.contao.org/manual/de/?search=%s`
```

2021-03-21 18:10 UTC, fritzmg commented on docs/manual/_index.en.md
> +- ``docs insterttags``
```suggestion
- `docs insterttags`
```

2021-03-22 08:11 UTC, fkaminski commented on docs/manual/_index.en.md
> -{{% /notice %}}
OK - Done.

2021-03-22 08:23 UTC, fritzmg requested changes

2021-03-22 08:23 UTC, fritzmg commented on docs/manual/_index.en.md
> +You can browse the documentation here, but you can also use it directly in your favorite browser. For this you have to
```suggestion
You can search the documentation here, but you can also use it directly in your favorite browser. For this you have to
```

2021-03-22 08:52 UTC, fritzmg approved these changes

2021-04-19 13:41 UTC, netzarbeiter approved these changes
Thank you, Franko

2021-04-19 13:42 UTC, merged