Initial Guide XAMPP (DE)
contao/docs pull request #695
Opened 2021-03-24 15:02 UTC by fkaminski

See Issue #685
First German Commit. Translation (EN) after review(s).
Thanks

2021-03-26 16:45 UTC, fkaminski commented
Add commit with EN translation (via deepl).

2021-04-28 09:10 UTC, netzarbeiter requested changes
Thank you, Franko

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Du solltest das "XAMPP Control-Panel" (xampp-control.exe) und die »XAMPP Konsole« (xampp_shell.bat) immer mit
```suggestion
Du solltest das »XAMPP Control-Panel« (xampp-control.exe) und die »XAMPP Konsole« (xampp_shell.bat) immer mit 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +## Die PHP Konfiguration
```suggestion
## Die PHP-Konfiguration
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Darüber hinaus könnstest du optional auch die Einträge »allow_url_fopen«, »max_execution_time«
```suggestion
Darüber hinaus könntest du optional auch die Einträge »allow_url_fopen«, »max_execution_time« 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Du hast alle Vorbereitungen für eine lokale Contao Installation abgeschlossen.
```suggestion
Du hast alle Vorbereitungen für eine lokale Installation von Contao abgeschlossen.
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +PHP-Composer Datei ebenfalls lediglich kopieren.
```suggestion
PHP-Composer-Datei ebenfalls lediglich kopieren. 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +In der »XAMPP-Konsole« wechselst du daher in dieses Unterverzeichnis und installierst eine Contao Version
```suggestion
In der »XAMPP-Konsole« wechselst du daher in dieses Unterverzeichnis und installierst eine Contao-Version 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Deine Contao Installation befindet sich im Anschluss im XAMPP-Verzeichnis `htdocs\demo`.
```suggestion
Deine Contao-Installation befindet sich im Anschluss im XAMPP-Verzeichnis `htdocs\demo`.
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Diese Vorgehensweise ist optional. Du könntest die Contao Installation auch direkt über den Contao-Manager ausführen.
```suggestion
Optional könntest du die Installation von Contao auch direkt über den Contao-Manager ausführen.
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Deine Contao Installation kann jetzt abgeschlossen werden. Allerdings unterscheiden sich die Contao Aufrufe, ohne
```suggestion
Deine Installation kann jetzt abgeschlossen werden. Allerdings unterscheiden sich die Contao-Aufrufe, ohne
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +## Contao Aufrufe (ohne eigenen vHost)
```suggestion
## Contao-Aufrufe (ohne eigenen vHost)
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +[Contao-Manager](/de/installation/contao-manager/) zwingend notwendig.
```suggestion
[Contao Manager](/de/installation/contao-manager/) zwingend notwendig. 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Diese Vorgehensweise ist optional. Du könntest die Contao Installation auch direkt über den Contao-Manager ausführen.
```suggestion
Diese Vorgehensweise ist optional. Du könntest die Installation auch direkt über den Contao Manager ausführen.
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +[Contao-Manager](https://contao.org/de/download.html) z. B. in das Verzeichnis `demo\web` und benennst die Datei danach
```suggestion
[Contao Manager](https://contao.org/de/download.html) z. B. in das Verzeichnis `demo\web` und benennst die Datei danach 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +berücksichtigst. Innerhalb der Contao eigenen Verlinkung (z. B.: Den Contao-Manager über das Backend starten usw.)
```suggestion
berücksichtigst. Innerhalb der Contao eigenen Verlinkung (z. B.: Den Contao Manager über das Backend starten usw.) 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +erhälst du weiterhin Fehlermeldungen, da diese von einer »korrekten« Umgebung ausgehen. Empfehlenswert wäre daher die
```suggestion
erhältst du weiterhin Fehlermeldungen, da diese von einer »korrekten« Umgebung ausgehen. Empfehlenswert wäre daher die
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Contao Installation(en) außerhalb des XAMPP-Verzeichnisses pflegen und andererseits diese mit eigenen, lokalen
```suggestion
Contao-Installation(en) außerhalb des XAMPP-Verzeichnisses pflegen und andererseits diese mit eigenen, lokalen
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Domain Namen verknüpfen.
```suggestion
Domain-Namen verknüpfen. 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Erstelle dir ein neues Verzeichnis z. B. `D:\vhost\demo\web`. Kopiere den [Contao-Manager](https://contao.org/de/download.html)
```suggestion
Erstelle dir ein neues Verzeichnis z. B. `D:\vhost\demo\web`. Kopiere den [Contao Manager](https://contao.org/de/download.html) 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +### Domain Namen erstellen
```suggestion
### Domain-Namen erstellen
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Wir möchten unsere Contao Installation über die Domain `demo.local` erreichen. Im Windows Verzeichnis `System32/drivers/etc`
```suggestion
Wir möchten unsere Contao-Installation über die Domain `demo.local` erreichen. Im Windows Verzeichnis `System32/drivers/etc`
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Passe hier nötigenfalls die Pfadangaben deinen aktuellen Verzeichnisse entsprechend an. Im »XAMPP Control-Panel«
```suggestion
Passe hier nötigenfalls die Pfadangaben deiner aktuellen Verzeichnisse entsprechend an. Im »XAMPP Control-Panel« 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +musst du die Module »Apache« und »MySQL« neu starten. Anschließend kannst du den Contao-Manager über den Aufruf
```suggestion
musst du die Module »Apache« und »MySQL« neu starten. Anschließend kannst du den Contao Manager über den Aufruf
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Mit dieser Vorgehensweise könntest du auch mehrere Contao Installationen über verschiedene, lokale Domain Namen mit
```suggestion
Mit dieser Vorgehensweise könntest du auch mehrere Contao-Installationen über verschiedene, lokale Domain-Namen mit 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +grundsätzlich beliebig. Lediglich die Angabe bei `Common Name` muss dem aktuellen, lokalen Domain Namen entsprechen.
```suggestion
grundsätzlich beliebig. Lediglich die Angabe bei `Common Name` muss dem aktuellen, lokalen Domain-Namen entsprechen. 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +In den Verzeichnissen `apache\conf\ssl.crt`, `apache\conf\ssl.csr` und `apache\conf\ssl.key` wurden den Angaben
```suggestion
In den Dateien `apache\conf\ssl.crt`, `apache\conf\ssl.csr` und `apache\conf\ssl.key` wurden den Angaben 
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +die Module »Apache« und »MySQL« erneut. Anschließend kannst du den Contao-Manager über `https://demo.local/contao-manager.phar`
```suggestion
die Module »Apache« und »MySQL« erneut. Anschließend kannst du den Contao Manager über `https://demo.local/contao-manager.phar.php`
```

2021-04-28 09:10 UTC, netzarbeiter commented on docs/manual/guides/local-installation/xampp.de.md
> +Im Contao-Manager selbst wird fortan der vorherige Hinweis auf eine »Unsichere Verbindung« nicht mehr erfolgen.
```suggestion
Im Contao Manager selbst wird fortan der vorherige Hinweis auf eine »Unsichere Verbindung« nicht mehr angezeigt.
```

2021-04-28 10:53 UTC, fkaminski commented
Thank you

2021-04-28 11:42 UTC, netzarbeiter approved these changes

2021-04-28 11:42 UTC, merged