Update of article-management/ and its sub pages
contao/docs pull request #766
Opened 2021-06-04 07:23 UTC by fiedsch

* updated the .de.md files too (wehere I thought they were wrong)
* insert-tags.en.md was assigned to @toflar in No. 35 so no update here

2021-06-07 07:18 UTC, netzarbeiter requested changes
Thank you, Andreas

2021-06-07 07:18 UTC, netzarbeiter commented on docs/manual/article-management/articles.en.md
> +![The article management](/de/article-management/images/de/articlemanagement.png?classes=shadow)
```suggestion
![The article management](/de/article-management/images/en/articlemanagement.png?classes=shadow)
```
Bitte Bild in Ordner en verschieben

2021-06-07 07:18 UTC, netzarbeiter commented on docs/manual/article-management/articles.en.md
> +![Several articles with teaser text](/de/article-management/images/de/multiple-articles-with-teasertext.png?classes=shadow)
```suggestion
![Several articles with teaser text](/de/article-management/images/en/multiple-articles-with-teasertext.png?classes=shadow)
```
Bitte Bild in Ordner en verschieben

2021-06-07 07:20 UTC, fiedsch commented
OK. I'll move the images and adapt the paths. Will have time for that (probably) tonight.

2021-06-08 05:30 UTC, fiedsch commented
Thanks for cross checking, Bjarke. Here you go.

2021-06-08 05:56 UTC, netzarbeiter approved these changes

2021-06-08 05:56 UTC, merged