Improve move contao section (hackaton, task 8)
contao/docs pull request #768
Opened 2021-06-04 12:06 UTC by m-vo

This improves the "Move Contao" section.

* I wasn't really happy with the original document so I restructured it, made use of the tab feature and removed redundant content (see installation).
* I also adjusted the args of the dump/import commands because they were IMO easy to get wrong (no space in `-uUsername` for instance) or potentially generating bad files (missing `--hex-blob`).

These two things should get reviewed first IMO, because we likely want to port them to the German version as well.

Images will be adjusted by @stefansl in a followup PR.

2021-06-04 12:14 UTC, m-vo commented on docs/manual/installation/move-contao.en.md
> +{{< tabs >}}
@fritzmg Would this need a tab group id? If so, how would this look?

2021-06-07 12:59 UTC, netzarbeiter requested changes
Thank you, Moritz. Can you please adjust the german version too.

2021-06-07 12:59 UTC, netzarbeiter commented on docs/manual/installation/move-contao.en.md
> +To reduce the risk of conflicts, make sure your source and target server both run the **[same PHP version](/en/installation/system-requirements/#minimum-php-requirements)**.
```suggestion
To reduce the risk of conflicts, make sure your source and target server both run the **[same PHP version](../system-requirements/#minimum-php-requirements)**.
```

2021-06-07 13:09 UTC, m-vo commented on docs/manual/installation/move-contao.en.md
> +To reduce the risk of conflicts, make sure your source and target server both run the **[same PHP version](/en/installation/system-requirements/#minimum-php-requirements)**.
adjusted in 2570672

2021-06-07 13:13 UTC, netzarbeiter approved these changes

2021-06-07 13:14 UTC, merged