Improvements for the Twig section
contao/docs pull request #804
Opened 2021-08-02 16:29 UTC by m-vo

Closes #803 + adds a note clarifying when you can omit a template's file extension.

2021-08-02 21:53 UTC, fritzmg requested changes

2021-08-02 21:53 UTC, fritzmg commented on docs/dev/framework/templates/twig.md
> +When extending/including/embedding templates from the `@Contao` namespace,
```suggestion
When extending, including or embedding templates from the `@Contao` namespace,
```

2021-08-20 00:36 UTC, m-vo commented
Is there anything missing to get this PR merged? ☺️

2021-09-02 15:56 UTC, m-vo commented
ping @fritzmg

2021-09-03 07:12 UTC, ausi approved these changes

2021-09-03 07:59 UTC, fritzmg approved these changes

2021-09-03 07:59 UTC, merged

2021-09-03 07:59 UTC, fritzmg commented
Thank you @m-vo :)