Update system-requirements.de.md
contao/docs pull request #814
Opened 2021-08-21 12:47 UTC by xchs

Add the information about the MySQL strict mode.

2021-08-21 21:49 UTC, ausi approved these changes

2021-08-31 05:56 UTC, netzarbeiter requested changes
Thank you, Hannes

2021-08-31 05:56 UTC, netzarbeiter commented on docs/manual/installation/system-requirements.de.md
> +Ab **Contao 4.12** zeigt das Install-Tool eine Warnmeldung an, wenn der Datenbankserver nicht im
```suggestion
Ab **Contao 4.9** zeigt das Install-Tool eine Warnmeldung an, wenn der Datenbankserver nicht im
```

2021-08-31 20:51 UTC, fritzmg approved these changes

2021-09-01 04:18 UTC, netzarbeiter approved these changes

2021-09-01 04:19 UTC, merged