Update XML-Sitemap
contao/docs pull request #822
Opened 2021-09-03 12:49 UTC by Anke

added note "ab Version 11"

2021-09-03 13:10 UTC, fritzmg requested changes

2021-09-03 13:10 UTC, fritzmg commented on docs/manual/layout/site-structure/configure-pages.de.md
> +{{< version-tag "4.11" >}} Die Sitemap ist ab Contao 4.11 automatisch pro Domain verfügbar. Hat man mehrere Sprachen unter einer einzigen Domain, sind alle Links in dieser Sitemap enthalten.
```suggestion
{{% notice "info" %}}
Die Sitemap ist ab Contao 4.11 automatisch pro Domain verfügbar. Hat man mehrere Sprachen unter einer einzigen Domain, sind alle Links in dieser Sitemap enthalten.
{{% /notice %}}
```

I think we should to a full notice.

2021-09-24 09:43 UTC, netzarbeiter approved these changes
Thank you, Anke

2021-09-24 09:44 UTC, fritzmg approved these changes

2021-09-24 09:44 UTC, merged