Add list wizard documentation
contao/docs pull request #869
Opened 2021-11-03 12:21 UTC by koertho

In this PR I tried myself on the list widget documentation.

I couldn't test it, as there are errors when trying to compile.

2021-11-04 21:04 UTC, fritzmg requested changes
Thank you and looks good to me, apart from a few minor nitpicks 👍 

Compiles fine with Hugo 0.88.1 on my system too.

2021-11-04 21:04 UTC, fritzmg commented on docs/dev/reference/widgets/list-wizard.md
> +| `eval.maxlength` | `integer` | Maximum number of characters that are allowed in list fields.|
```suggestion
| `eval.maxlength` | `integer` | Maximum number of characters that are allowed in list fields. |

```

2021-11-04 21:04 UTC, fritzmg commented on docs/dev/reference/widgets/list-wizard.md
> +    'sql' => 'blob NULL',
```suggestion
    'sql' => [
        'type' => 'blob',
        'notnull' => false
    ],

```

2021-11-04 21:04 UTC, fritzmg commented on docs/dev/reference/widgets/list-wizard.md
> +This widget renders a list wizard which allows to add, remove and reorder list items.
```suggestion
This widget renders a list wizard which allows you to add, remove and reorder list items.

```

2021-11-04 21:04 UTC, fritzmg commented on docs/dev/reference/widgets/list-wizard.md
> +Usage in list content element:
```suggestion
Usage in the list content element: 

```

2021-11-05 08:26 UTC, koertho commented
@fritzmg Thanks for your suggestions, I added them. From my point, the PR ist ready :)

2021-11-05 08:45 UTC, fritzmg approved these changes

2021-11-05 08:45 UTC, merged

2021-11-05 08:45 UTC, fritzmg commented
Thank you @koertho :)