Guide: DCA Adjustments
contao/docs pull request #887
Opened 2021-11-25 14:10 UTC by fkaminski

Starting Samples (DE).
(Not yet categorized. Will be easier when more content is available)

2021-11-26 10:17 UTC, fkaminski commented
As discussed, additional categorization would be useful. Suggestion: 
Categorization by table name e.g. tl_content.php, tl_news.php etc..?

2021-11-26 10:48 UTC, fiedsch commented
> Categorization by table name e.g. tl_content.php, tl_news.php etc..?

I'm not sure if this is a good idea, as many adjustments are the same for all tables. Think of "making a field mandatory".
So maybe rather categorization by "type of change" (without having an idea how this could be called).

2021-11-26 11:01 UTC, fkaminski commented
> ... without having an idea how this could be called)

Same with me :-)

2021-12-13 13:31 UTC, netzarbeiter requested changes
Thank you, Franko

2021-12-13 13:31 UTC, netzarbeiter commented on docs/manual/guides/dca-adjustments.de.md
> +nicht existieren, musst du diese zunächst erstellen. Für jede Contao Tabelle benötigst du eine eigene Datei,
```suggestion
nicht existieren, musst du diese zunächst erstellen. Für jede Contao-Tabelle benötigst du eine eigene Datei, 
```

2021-12-13 13:31 UTC, netzarbeiter commented on docs/manual/guides/dca-adjustments.de.md
> +[Contao-Manager](/de/installation/contao-manager/) oder über die Konsole neu aufbauen. Dieser Schritt ist nach
```suggestion
[Contao Manager](/de/installation/contao-manager/) oder über die Konsole neu aufbauen. Dieser Schritt ist nach 
```

2021-12-15 15:01 UTC, netzarbeiter approved these changes

2021-12-15 15:01 UTC, merged