Update xampp.de.md
contao/docs pull request #899
Opened 2021-12-16 21:33 UTC by mlwebworker

Anpassungen der httpd.conf wegen Problemen mit Contao 4.12 (Installtool) unter PHP8. Die Probleme müssen sich aber nicht nur auf das Szenario beschränken

2021-12-16 21:37 UTC, mlwebworker commented
Wenn die Änderung soweit ok ist, kann diese fast genauso für Laragon übernommen werden. Leider kenne ich dort die Pfade nicht, aber das Problem ist das Gleiche.

2021-12-17 05:21 UTC, fiedsch commented on docs/manual/guides/local-installation/xampp.de.md
Du hast den „öffnenden Code Block“ (die drei Backticks) entfernt und dafür eine „notice“ geöffnet. Weiter unten wird der Code Block geschlossen, die notice aber nirgends. Da kann irgendetwas nicht stimmen.

2021-12-17 08:55 UTC, mlwebworker commented on docs/manual/guides/local-installation/xampp.de.md
Irgendwie stehe ich mit dem Markup noch auf Kriegsfuss.

2021-12-17 09:23 UTC, fiedsch commented on docs/manual/guides/local-installation/xampp.de.md
> +{{% notice info %}}
```suggestion
```php
```

2021-12-17 09:30 UTC, mlwebworker commented
Danke @fiedsch 
Ich habe es eben nicht hingekriegt, das selbst zu ändern. Ich glaub ich brauche dazu eine Schulung. Ich habe mit gitbub noch nie im Team gearbeitet und für meine eigenen repositorys nutze ich Bitbucket.
Oben habe ich nämlich leider auch noch den Hinweis vergessen, dass man den Apache/XAMPP nach der Anpassung neu starten muss.

2021-12-17 09:30 UTC, fiedsch commented on docs/manual/guides/local-installation/xampp.de.md
Du hattest `{{% notice info %}}` wo zuvor ` ```php` stand. Dadurch hätten wir -- wenn ich nichts übersehen habe -- zwei Fehler:
* Durch das fehlende öffnende ` ```php` wird der Code für die Apache Konfiguration nicht als Code  formatiert. Weiter unten ist aber das schließende ` ```` noch vorhanden. Damit kommen open- und close-"Tags" durcheinander.
* Das öffnende `{{% notice info %}}` wird nicht geschlossen. Da schließende `{{% /notice %}}`fehlt.

2021-12-17 09:33 UTC, fiedsch commented on docs/manual/guides/local-installation/xampp.de.md
> +{{% notice info %}}
Oder 
```
  {{% notice info %}}
  ```php
```
und am Ende des Code-Blocks dann  
```
  ```
  {{% /notice %}}
```
um den gesammten Code-Block mit einer `notice` zu "wrappen".

2021-12-17 09:36 UTC, fiedsch commented
Wenn Du die Änderungen machst und in Deinen Fork committest, sollte der Pull-Request hier aktualisiert werden.

2021-12-17 09:41 UTC, fritzmg requested changes

2021-12-17 09:41 UTC, fritzmg commented on docs/manual/guides/local-installation/xampp.de.md
> +Bei XAMPP bzw. Apache unter Windows ist der Default-Wert der sogenannten ThreadStackSize nur 1MB, während der Wert auf Linux-Plattformen standardmäßig bei 8MB liegt. Um Abstürze des lokalen Servers z
```suggestion
## Die Appache-Konfiguration

Bei XAMPP bzw. Apache unter Windows ist der Default-Wert der sogenannten ThreadStackSize nur 1MB, während der Wert auf Linux-Plattformen standardmäßig bei 8MB liegt. Um Abstürze des lokalen Servers zu vermeiden, wird empfohlen diesen Wert zu erhöhen.
```

2021-12-17 09:51 UTC, fritzmg requested changes

2021-12-17 09:51 UTC, fritzmg commented on docs/manual/guides/local-installation/xampp.de.md
> +```php
Since it's not PHP I would remove the `php`.

2021-12-17 09:59 UTC, fritzmg requested changes

2021-12-17 09:59 UTC, fritzmg commented on docs/manual/guides/local-installation/xampp.de.md
> +Ergänze dazu die Datei D:\xampp\apache\conf\httpd.conf am Ende durch folgenden Code um die ThreadThreadStackSize auf 8MB zu erhöhen
```suggestion
Bei XAMPP bzw. Apache unter Windows ist der Default-Wert der sogenannten `ThreadStackSize` nur 1MB, während der Wert auf Linux-Plattformen standardmäßig bei 8MB liegt. Um Abstürze des lokalen Servers zu vermeiden, wird empfohlen diesen Wert zu erhöhen.
Ergänze dazu die Datei C:\xampp\apache\conf\httpd.conf am Ende durch folgenden Code um die `ThreadThreadStackSize` auf 8MB zu erhöhen 
```

`C:` is probably the standard path 🙃

2021-12-17 10:34 UTC, xchs commented on docs/manual/guides/local-installation/xampp.de.md
> +## Die Appache-Konfiguration
```suggestion
## Die Apache-Konfiguration
```

2021-12-17 10:35 UTC, xchs commented on docs/manual/guides/local-installation/xampp.de.md
> +Bei XAMPP bzw. Apache unter Windows ist der Default-Wert der sogenannten ThreadStackSize nur 1MB, während der Wert auf Linux-Plattformen standardmäßig bei 8MB liegt. Um Abstürze des lokalen Servers z
```suggestion
Bei XAMPP bzw. Apache unter Windows ist der Default-Wert der sogenannten ThreadStackSize nur 1 MB, während der Wert auf Linux-Plattformen standardmäßig bei 8 MB liegt. Um Abstürze des lokalen Servers zu vermeiden, wird empfohlen, diesen Wert zu erhöhen.
```

2021-12-17 10:36 UTC, xchs commented on docs/manual/guides/local-installation/xampp.de.md
> +Ergänze dazu die Datei D:\xampp\apache\conf\httpd.conf am Ende durch folgenden Code um die ThreadThreadStackSize auf 8MB zu erhöhen
```suggestion
Ergänze dazu die Datei `D:\xampp\apache\conf\httpd.conf` am Ende durch folgenden Code, um die ThreadThreadStackSize auf 8 MB zu erhöhen 
```

2021-12-17 10:49 UTC, fritzmg approved these changes

2021-12-17 15:26 UTC, netzarbeiter approved these changes
Thank you, Maren

2021-12-17 15:26 UTC, merged