Change link to Markdown Syntax
contao/docs pull request #908
Opened 2021-12-19 11:22 UTC by fkaminski

... to https://github.com/contao/docs/blob/main/CONTRIBUTING.md

2021-12-19 12:25 UTC, fkaminski commented
Last 2 commits with info about how to edit further changes before PR.

2021-12-19 14:49 UTC, xchs commented on docs/manual/contributing/_index.de.md
> +Im Anschluß kannst du dann abschließend den Pull-Request über »Contribute/Open pull request« starten.
```suggestion
Im Anschluss kannst du dann abschließend den Pull-Request über »Contribute/Open pull request« starten.
```

2021-12-19 14:49 UTC, xchs commented on docs/manual/contributing/_index.en.md
> +a request to the repository's authorizers to "pull" your changes into the official repository.
```suggestion
request to the repository's authorizers to "pull" your changes into the official repository. 
```

2021-12-19 14:49 UTC, xchs commented on docs/manual/contributing/_index.en.md
> +"to pull" your changes into the official repository.
```suggestion
```

2021-12-20 08:40 UTC, fritzmg requested changes

2021-12-20 08:40 UTC, fritzmg commented on docs/manual/contributing/_index.de.md
> +»ziehen« (engl. »to pull«).
Pull Requests sind ein Feature auf GitHub und haben nichts mit Git an sich zu tun. Zudem heißt das Feature auf GitHub und GitBucket "Pull Request" und auf GitLab und Gitorious zB "Merge Request".

Auch woher Name "Pull Request" kommt ist zumindest laut [diesem Stackoverflow Eintrag](https://stackoverflow.com/a/29951658/374996) und dessen Kommentaren nicht ganz klar.

2021-12-20 09:49 UTC, fkaminski commented on docs/manual/contributing/_index.de.md
> +»ziehen« (engl. »to pull«).
Diese Info war ja schon da? Evtl. dann ganz weglassen oder minimiert für GitHub allgemein:

> Da du keine Berechtigungen hast, direkt Änderungen im offiziellen Repository zu vollziehen, stellst du 
> eine Anfrage an die Berechtigten des Repositories, deine Änderungen in das offizielle Repository zu übernehmen.
>

2021-12-20 10:24 UTC, fritzmg commented on docs/manual/contributing/_index.de.md
> +»ziehen« (engl. »to pull«).
> Diese Info war ja schon da?

Mir ist es nur jetzt im Zuge deines PR aufgefallen.

2021-12-21 15:30 UTC, netzarbeiter approved these changes
Thank you, Franko

2021-12-21 15:31 UTC, merged