Add new content element "Custom template" (marked 4.13)
contao/docs pull request #912
Opened 2021-12-21 14:33 UTC by fkaminski

DE/EN 
Hint: The german translation (regarding element name) is not final yet!

2021-12-21 14:49 UTC, fritzmg requested changes

2021-12-21 14:49 UTC, fritzmg commented on docs/manual/article-management/content-elements.de.md
> +{{< version "4.13" >}}
```suggestion
{{< version "4.13" >}}

Das Inhaltselement »Custom template« bietet die Möglichkeit beliebige Templates auszuwählen und dabei 
eigene, individuelle Platzhalter zu definieren die im jeweiligen Template ausgegeben werden können.

| Info |   |
| ---- | - |
| **Template data:** | Angabe eines oder mehrerer Schlüssel/Wert Paare zur Ausgabe im Template. |
| **Inhaltselement-Template:** | Hier kannst du das Standard-Template `ce_template` überschreiben. |
```

2021-12-21 14:49 UTC, fritzmg commented on docs/manual/article-management/content-elements.en.md
> +{{< version "4.13" >}}
```suggestion
{{< version "4.13" >}}

The content element »Custom template« offers the possibility to select any template and to define your own, 
individual placeholders which can be output in the respective template.

| Info |   |
| ---- | - |
| **Template data:** | Specification of one or more key/value pairs. |
| **Content element template:** | Here you can overwrite the default template `ce_template`. |
```

2021-12-22 16:38 UTC, xchs commented on docs/manual/article-management/content-elements.de.md
> +Das Inhaltselement »Custom template« bietet die Möglichkeit ein Template auszuwählen und dabei individuelle
```suggestion
Das Inhaltselement »Custom template« bietet die Möglichkeit, ein Template auszuwählen und dabei individuelle 
```

2021-12-22 16:38 UTC, xchs commented on docs/manual/article-management/content-elements.de.md
> +Platzhalter zu definieren die im jeweiligen Template ausgegeben werden können.
```suggestion
Platzhalter zu definieren, die im jeweiligen Template ausgegeben werden können.
```

2022-01-18 13:56 UTC, fkaminski commented
Requires observation: See: [#3950](https://github.com/contao/contao/issues/3950)

2022-01-19 15:33 UTC, netzarbeiter commented
I close this pull request because of https://github.com/contao/docs/pull/933.

2022-01-19 15:52 UTC, fkaminski commented
Please reopen this.
This pull request documents the new content element.
#933 is about the new module.

(Even if the final german translation is not sure yet (see #3950))

2022-01-25 12:36 UTC, fritzmg approved these changes

2022-01-26 11:53 UTC, fkaminski commented
Tried to fix conflicts because of #943. Hope this will work ...

2022-01-26 14:25 UTC, netzarbeiter approved these changes
Thank you, Franko

2022-01-26 14:26 UTC, merged