Consistently name file extension yml
contao/docs pull request #924
Opened 2022-01-04 16:53 UTC by fiedsch

In most places of the docs the configuration file is called `config/config.yml` as opposed to `config/config.yaml`. For consistency reasons I would find it clearer to use the `.yml` file name extension throughout. This PR tries to fix this.

Opinions please.

2022-01-04 17:21 UTC, fritzmg requested changes
The official file extension for YAML is `.yaml`: https://yaml.org/faq.html
Symfony also follows this recommendation and so should Contao. I alredy normalised this for the dev docs in https://github.com/contao/docs/commit/31d3bfdd1336c82a049d229ab464d8b61ed82fed.

However the docs as well as Contao's source code still reference `.yml` a lot, yes.

2022-01-04 17:52 UTC, fiedsch commented
So, you mean the PR should go the other direction. Should I prepare a new one for that? Maybe including an explanation on `.yml` vs `.yaml`.

2022-01-04 18:17 UTC, fritzmg commented
Yes, the recommendation is `.yaml`. Feel free to make a suggestion :)

2022-01-04 18:53 UTC, fiedsch commented
And just to be sure: Contao—as it is based on Symfony—will also work with `.yaml` files without further changes? I never tried that …

On the other hand, there are numerous references to `.yml` files in Contao‘s language files (e.g. https://github.com/contao/contao/blob/e107ce4f1aa55c65a86d9c2256c193730e7520fb/installation-bundle/src/Resources/translations/ContaoInstallationBundle.de.xlf#L317) that would have to be changed also. Otherwise I would expect a lot of confused users.

2022-01-04 19:51 UTC, fritzmg commented
> And just to be sure: Contao—as it is based on Symfony—will also work with .yaml files without further changes? I never tried that …

Yes, both Symfony and Contao support both extensions.

> On the other hand, there are numerous references to .yml files in Contao‘s language files (e.g. https://github.com/contao/contao/blob/e107ce4f1aa55c65a86d9c2256c193730e7520fb/installation-bundle/src/Resources/translations/ContaoInstallationBundle.de.xlf#L317) that would have to be changed also. Otherwise I would expect a lot of confused users.

Yes, as I said, Contao itself still references just `.yml` in some places, which should be changed.

2022-01-05 05:09 UTC, fiedsch commented
> Yes, as I said, Contao itself still references just .yml in some places, which should be changed.

So I am closing this for now, because I don‘t think it makes sense to be ahead of the current state of Contao in the documentation.

2022-01-05 05:09 UTC, closed without merging

2022-01-05 08:10 UTC, fritzmg commented
> because I don‘t think it makes sense to be ahead of the current state of Contao in the documentation.

But then your PR should stay open? ;)

2022-01-05 11:57 UTC, fiedsch commented
If we decide to go with the `.yaml` file extension my PR would be wrong. So I thought closing is appropriate.