Draft: Some layout/navi changes within content elements
contao/docs pull request #943
Opened 2022-01-23 15:04 UTC by fkaminski

As addressed in slack, a draft regarding changes to content elements representations.

-  New navigation/split of content elements according to the backend
- Some settings have already been consistently formatted via tables

If desired, I would also format the other areas accordingly uniformly ...

2022-01-24 10:46 UTC, fkaminski commented
As discussed in the clarifying Slack Huddle with Bjarke, we could do the Navi split. Further changes to the formatting are not necessary.

2022-01-25 06:09 UTC, netzarbeiter commented
Why didn't you just make the changes we discussed?

2022-01-25 07:28 UTC, fkaminski commented
Will remove the last two commits with the table format today.

2022-01-25 07:48 UTC, fkaminski commented
Removed table format/Back to original format with last commit ...

2022-01-26 06:18 UTC, netzarbeiter requested changes
Thank you, Franko

2022-01-26 06:18 UTC, netzarbeiter commented on docs/manual/article-management/content-elements/accordion.de.md
> +title: "Akkordion"
```suggestion
title: "Akkordeon"
```

2022-01-26 06:18 UTC, netzarbeiter commented on docs/manual/article-management/content-elements/accordion.de.md
> +description: "Inhaltselemente im Bereich Akkordion"
```suggestion
description: "Inhaltselemente im Bereich Akkordeon"
```

2022-01-26 06:18 UTC, netzarbeiter commented on docs/manual/article-management/content-elements/accordion.de.md
> +url: "artikelverwaltung/inhaltselemente/akkordion"
```suggestion
url: "artikelverwaltung/inhaltselemente/akkordeon"
```

2022-01-26 06:18 UTC, netzarbeiter commented on docs/manual/article-management/content-elements/accordion.de.md
> +    - /de/artikelverwaltung/inhaltselemente/akkordion/
```suggestion
    - /de/artikelverwaltung/inhaltselemente/akkordeon/
```

2022-01-26 07:57 UTC, netzarbeiter approved these changes

2022-01-26 07:57 UTC, merged