Add cli command contao:crawl
contao/docs pull request #963
Opened 2022-01-28 15:53 UTC by fkaminski

Some translations are not so elegant. Suggestions are welcome ...

2022-01-28 16:58 UTC, netzarbeiter requested changes
Thank you, Franko

2022-01-28 16:58 UTC, netzarbeiter commented on docs/manual/cli/crawl.de.md
> +Dabei können eine beliebige Anzahl von sogenannten »Subscribern« die Ergebnisse der HTTP Anfragen abonnieren und
```suggestion
Dabei können eine beliebige Anzahl von sogenannten »Subscribern« die Ergebnisse der HTTP-Anfragen abonnieren und 
```

2022-01-28 16:58 UTC, netzarbeiter commented on docs/manual/cli/crawl.de.md
> +Der Crawler durchforstet im wesentlichen alle von Contao generierten URLs, wie jede andere Suchmaschiene. Er folgt Links,
```suggestion
Der Crawler durchforstet im wesentlichen alle von Contao generierten URLs, wie jede andere Suchmaschine. Er folgt Links, 
```

2022-01-28 16:58 UTC, netzarbeiter commented on docs/manual/cli/crawl.de.md
> +```sh
```suggestion
```bash
```

2022-01-28 16:58 UTC, netzarbeiter commented on docs/manual/cli/crawl.de.md
> +$> php vendor/bin/contao-console contao:crawl [options] [<job>]
```suggestion
php vendor/bin/contao-console contao:crawl [options] [<job>]
```

2022-01-28 16:58 UTC, netzarbeiter commented on docs/manual/cli/crawl.en.md
> +```sh
```suggestion
```bash
```

2022-01-28 16:58 UTC, netzarbeiter commented on docs/manual/cli/crawl.en.md
> +$> php vendor/bin/contao-console contao:crawl [options] [<job>]
```suggestion
php vendor/bin/contao-console contao:crawl [options] [<job>]
```

2022-01-29 14:09 UTC, netzarbeiter approved these changes

2022-01-29 17:16 UTC, fritzmg approved these changes

2022-01-31 05:15 UTC, merged