Add section about changing php verisons
contao/docs pull request #974
Opened 2022-01-30 16:04 UTC by fritzmg

See #973

2022-01-31 08:31 UTC, Toflar requested changes
Can we have a reason as to why this is required? Just a simple sentence about the fact that platform requirements are also considered in Composer? Otherwise you only know that you have to do it but you don't understand why.

2022-01-31 08:38 UTC, fritzmg commented
Well, it already says

> This ensures compatibility of your installed packages with the respective PHP version.

but I'd expand it then to

> This ensures compatibility of your installed packages with the respective PHP version, since each package (including Contao itself, installed Contao extensions and other third-party packages) can require a specific PHP version that it is known to be compatible with.

wdyt?

2022-01-31 08:42 UTC, Toflar commented
👍 Maybe also "and certain PHP extensions".

2022-01-31 09:44 UTC, Toflar approved these changes

2022-01-31 09:44 UTC, netzarbeiter requested changes
Thank you, Fritz

2022-01-31 09:44 UTC, netzarbeiter commented on docs/manual/installation/system-requirements.de.md
> +(inklusive Contao selbst, installierte Contao Extensions oder Dritt-Pakete) nach spezifischen PHP Versionen und PHP Extensions verlangen
```suggestion
(inklusive Contao selbst, installierte Contao-Extensions oder Dritt-Pakete) nach spezifischen PHP-Versionen und PHP-Extensions verlangen
```

2022-01-31 09:54 UTC, netzarbeiter approved these changes

2022-02-01 21:02 UTC, FelixOliverLange commented
I'm really not an expert on PHP nor on composer, so please forgive me my ignorance. But wouldn't running the update be required before the PHP version switch @fritzmg? After all, the dependencies must support the respective version before it is being run, otherwise the dependency incompatibility is noted by composer if you e.g. attempt an update or try to add an unrelated package.

2022-02-01 21:27 UTC, fritzmg commented
@FelixOliverLange composer installs the dependencies for which ever PHP version it detects. Thus running a package update before you switch will not change anything (unless you are overriding the PHP version in your `composer.json`). Also updating the dependencies to reflect a newer PHP version change _before_ you actually switch to a new PHP version will break the application even more likely, since you might then get packages that are incompatible with your _current_ PHP version.

2022-02-07 12:27 UTC, netzarbeiter approved these changes
Thank you, Fritz

2022-02-07 12:27 UTC, merged